"""add_soft_delete_to_geofence_location

Revision ID: 03453f028a5e
Revises: 85637d645afe
Create Date: 2026-02-05 20:15:08.812297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03453f028a5e'
down_revision: Union[str, Sequence[str], None] = '85637d645afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geofence_locations', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('geofence_locations', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_geofence_locations_is_deleted'), 'geofence_locations', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_geofence_locations_is_deleted'), table_name='geofence_locations')
    op.drop_column('geofence_locations', 'deleted_at')
    op.drop_column('geofence_locations', 'is_deleted')
    # ### end Alembic commands ###
