"""add_auth_fields_to_employee

Revision ID: 12345abcdef0
Revises: 6ffa086aab4f
Create Date: 2026-04-04 17:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12345abcdef0'
down_revision = '6ffa086aab4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('reset_password_token', sa.String(length=500), nullable=True))
    op.add_column('employees', sa.Column('reset_password_token_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'reset_password_token_expires_at')
    op.drop_column('employees', 'reset_password_token')
    op.drop_column('employees', 'hashed_password')
    # ### end Alembic commands ###
