"""add soft delete to department goals

Revision ID: 1d1f21455301
Revises: eac475b66340
Create Date: 2026-06-07 15:54:39.230344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d1f21455301'
down_revision: Union[str, Sequence[str], None] = 'eac475b66340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department_goals', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('department_goals', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department_goals', 'deleted_at')
    op.drop_column('department_goals', 'is_deleted')
    # ### end Alembic commands ###
