"""Add soft delete to ShiftAssignment

Revision ID: 258807bdb0ca
Revises: 9da93a7afdbe
Create Date: 2026-01-31 14:24:10.700234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '258807bdb0ca'
down_revision: Union[str, Sequence[str], None] = '9da93a7afdbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_assignments', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('shift_assignments', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shift_assignments', 'deleted_at')
    op.drop_column('shift_assignments', 'is_deleted')
    # ### end Alembic commands ###
