"""Add password fields to organization

Revision ID: 2d359c865d5f
Revises: 72b9b22c2bbe
Create Date: 2026-01-10 16:34:35.304747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d359c865d5f'
down_revision: Union[str, Sequence[str], None] = '72b9b22c2bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('organization', sa.Column('reset_password_token', sa.String(length=100), nullable=True))
    op.add_column('organization', sa.Column('reset_password_token_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'reset_password_token_expires_at')
    op.drop_column('organization', 'reset_password_token')
    op.drop_column('organization', 'hashed_password')
    # ### end Alembic commands ###
