"""Make payroll_audit_logs performed_by nullable

Revision ID: 30046b120e38
Revises: f33bd7cae80a
Create Date: 2026-05-16 17:09:40.826032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '30046b120e38'
down_revision: Union[str, Sequence[str], None] = 'f33bd7cae80a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payroll_audit_logs', 'performed_by',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payroll_audit_logs', 'performed_by',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
