"""add_soft_delete_to_job_titles

Revision ID: 3927c49ff767
Revises: 87fcd4740066
Create Date: 2026-01-10 22:50:05.598423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3927c49ff767'
down_revision: Union[str, Sequence[str], None] = '87fcd4740066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_titles', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('job_titles', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_titles', 'deleted_at')
    op.drop_column('job_titles', 'is_deleted')
    # ### end Alembic commands ###
