"""Add performance management models

Revision ID: 3b1877d23329
Revises: 8b688c22718e
Create Date: 2026-05-25 23:47:50.170203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.organization



# revision identifiers, used by Alembic.
revision: str = '3b1877d23329'
down_revision: Union[str, Sequence[str], None] = '8b688c22718e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competency_frameworks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_core', sa.Boolean(), nullable=True),
    sa.Column('proficiency_levels', sa.JSON(), nullable=False),
    sa.Column('behavioral_indicators', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_competency_name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_competency_org_active', 'competency_frameworks', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_competency_frameworks_organization_id'), 'competency_frameworks', ['organization_id'], unique=False)
    op.create_table('goal_alignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('parent_goal_type', sa.Enum('ORGANIZATION', 'DEPARTMENT', 'TEAM', 'INDIVIDUAL', name='goaltype'), nullable=False),
    sa.Column('parent_goal_id', sa.Integer(), nullable=False),
    sa.Column('child_goal_type', sa.Enum('ORGANIZATION', 'DEPARTMENT', 'TEAM', 'INDIVIDUAL', name='goaltype'), nullable=False),
    sa.Column('child_goal_id', sa.Integer(), nullable=False),
    sa.Column('alignment_weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_goal_type', 'parent_goal_id', 'child_goal_type', 'child_goal_id', name='uq_goal_alignment')
    )
    op.create_index('idx_goal_align_child', 'goal_alignments', ['child_goal_type', 'child_goal_id'], unique=False)
    op.create_index('idx_goal_align_parent', 'goal_alignments', ['parent_goal_type', 'parent_goal_id'], unique=False)
    op.create_table('goal_frameworks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('framework_type', sa.Enum('OKR', 'SMART', 'KPI', 'CUSTOM', name='goalframeworktype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('max_objectives_per_employee', sa.SmallInteger(), nullable=True),
    sa.Column('max_key_results_per_objective', sa.SmallInteger(), nullable=True),
    sa.Column('require_specific', sa.Boolean(), nullable=True),
    sa.Column('require_measurable', sa.Boolean(), nullable=True),
    sa.Column('require_time_bound', sa.Boolean(), nullable=True),
    sa.Column('goal_weight_enabled', sa.Boolean(), nullable=True),
    sa.Column('default_scoring_method', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_goal_framework_org_name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_goal_framework_org', 'goal_frameworks', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_goal_frameworks_organization_id'), 'goal_frameworks', ['organization_id'], unique=False)
    op.create_table('notification_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('notification_type', sa.Enum('CYCLE_STARTED', 'SELF_APPRAISAL_DUE', 'SELF_APPRAISAL_REMINDER', 'MANAGER_REVIEW_DUE', 'FEEDBACK_REQUEST', 'FEEDBACK_REMINDER', 'GOAL_DUE', 'APPRAISAL_PUBLISHED', 'PIP_CREATED', 'ONE_ON_ONE_REMINDER', 'CALIBRATION_SCHEDULED', name='notificationtype'), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_notif_template_name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_notification_templates_organization_id'), 'notification_templates', ['organization_id'], unique=False)
    op.create_table('rating_scales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('scale_points', sa.JSON(), nullable=False),
    sa.Column('min_value', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_value', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_rating_scale_name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_rating_scales_organization_id'), 'rating_scales', ['organization_id'], unique=False)
    op.create_table('appraisal_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('rating_scale_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('applicable_roles', sa.JSON(), nullable=True),
    sa.Column('applicable_departments', sa.JSON(), nullable=True),
    sa.Column('applicable_grades', sa.JSON(), nullable=True),
    sa.Column('goal_section_weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('competency_section_weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('behavior_section_weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('other_section_weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('self_appraisal_enabled', sa.Boolean(), nullable=True),
    sa.Column('self_rating_visible_to_manager', sa.Boolean(), nullable=True),
    sa.Column('employee_comments_enabled', sa.Boolean(), nullable=True),
    sa.Column('manager_override_enabled', sa.Boolean(), nullable=True),
    sa.Column('final_rating_formula', sa.String(length=100), nullable=True),
    sa.Column('version', sa.SmallInteger(), nullable=True),
    sa.Column('cloned_from_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cloned_from_id'], ['appraisal_templates.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['rating_scale_id'], ['rating_scales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_appraisal_template_name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_appraisal_template_org', 'appraisal_templates', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_appraisal_templates_organization_id'), 'appraisal_templates', ['organization_id'], unique=False)
    op.create_table('competency_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('grade_id', sa.Integer(), nullable=True),
    sa.Column('required_proficiency_level', sa.SmallInteger(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competency_frameworks.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['job_titles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_competency_mapping_dept', 'competency_mappings', ['department_id', 'competency_id'], unique=False)
    op.create_index('idx_competency_mapping_role', 'competency_mappings', ['role_id', 'competency_id'], unique=False)
    op.create_index(op.f('ix_competency_mappings_competency_id'), 'competency_mappings', ['competency_id'], unique=False)
    op.create_table('feedback_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('RATING', 'TEXT', 'MULTI_CHOICE', 'GOAL_RATING', 'COMPETENCY_RATING', name='questiontype'), nullable=False),
    sa.Column('provider_type', sa.Enum('SELF', 'PEER', 'SUBORDINATE', 'SUPERVISOR', 'EXTERNAL', name='feedbackprovidertype'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_anonymous_allowed', sa.Boolean(), nullable=True),
    sa.Column('competency_id', sa.Integer(), nullable=True),
    sa.Column('rating_scale_id', sa.Integer(), nullable=True),
    sa.Column('choices', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competency_frameworks.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['rating_scale_id'], ['rating_scales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_feedback_question_org', 'feedback_questions', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_feedback_questions_organization_id'), 'feedback_questions', ['organization_id'], unique=False)
    op.create_table('organization_goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('framework_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goal_type', sa.Enum('OKR', 'SMART', 'KPI', 'CUSTOM', name='goalframeworktype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.String(length=10), nullable=True),
    sa.Column('measurement_type', sa.Enum('NUMERIC', 'PERCENTAGE', 'BOOLEAN', 'MILESTONE', name='goalmeasurementtype'), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ON_TRACK', 'AT_RISK', 'BEHIND', 'COMPLETED', 'CANCELLED', name='goalstatus'), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('progress_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['framework_id'], ['goal_frameworks.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_org_goal_status_year', 'organization_goals', ['organization_id', 'status', 'fiscal_year'], unique=False)
    op.create_index(op.f('ix_organization_goals_organization_id'), 'organization_goals', ['organization_id'], unique=False)
    op.create_table('succession_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('position_title', sa.String(length=255), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('incumbent_employee_id', sa.Integer(), nullable=True),
    sa.Column('position_criticality', sa.String(length=20), nullable=True),
    sa.Column('plan_owner_id', sa.Integer(), nullable=False),
    sa.Column('review_frequency', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['incumbent_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['plan_owner_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['job_titles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_succession_plan_dept', 'succession_plans', ['department_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_succession_plans_organization_id'), 'succession_plans', ['organization_id'], unique=False)
    op.create_table('appraisal_cycles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('frequency', sa.Enum('ANNUAL', 'SEMI_ANNUAL', 'QUARTERLY', 'MONTHLY', 'CUSTOM', name='cyclefrequency'), nullable=False),
    sa.Column('fiscal_year', sa.String(length=10), nullable=True),
    sa.Column('review_period_start', sa.Date(), nullable=False),
    sa.Column('review_period_end', sa.Date(), nullable=False),
    sa.Column('goal_setting_start', sa.Date(), nullable=True),
    sa.Column('goal_setting_end', sa.Date(), nullable=True),
    sa.Column('self_appraisal_start', sa.Date(), nullable=False),
    sa.Column('self_appraisal_end', sa.Date(), nullable=False),
    sa.Column('manager_review_start', sa.Date(), nullable=False),
    sa.Column('manager_review_end', sa.Date(), nullable=False),
    sa.Column('calibration_start', sa.Date(), nullable=True),
    sa.Column('calibration_end', sa.Date(), nullable=True),
    sa.Column('result_publication_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'SELF_APPRAISAL', 'MANAGER_REVIEW', 'CALIBRATION', 'COMPLETED', 'ARCHIVED', name='cyclestatus'), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('rating_scale_id', sa.Integer(), nullable=False),
    sa.Column('include_probationary', sa.Boolean(), nullable=True),
    sa.Column('minimum_tenure_days', sa.Integer(), nullable=True),
    sa.Column('applicable_departments', sa.JSON(), nullable=True),
    sa.Column('applicable_employee_types', sa.JSON(), nullable=True),
    sa.Column('require_self_appraisal', sa.Boolean(), nullable=True),
    sa.Column('require_360_feedback', sa.Boolean(), nullable=True),
    sa.Column('require_calibration', sa.Boolean(), nullable=True),
    sa.Column('allow_employee_acknowledgment', sa.Boolean(), nullable=True),
    sa.Column('bell_curve_enabled', sa.Boolean(), nullable=True),
    sa.Column('bell_curve_config', sa.JSON(), nullable=True),
    sa.Column('reminders_enabled', sa.Boolean(), nullable=True),
    sa.Column('reminder_days_before', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['rating_scale_id'], ['rating_scales.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['appraisal_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_appraisal_cycle_name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_appraisal_cycle_org_status', 'appraisal_cycles', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_appraisal_cycles_organization_id'), 'appraisal_cycles', ['organization_id'], unique=False)
    op.create_table('appraisal_sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('section_order', sa.SmallInteger(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('visible_to_employee', sa.Boolean(), nullable=True),
    sa.Column('visible_to_manager', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['appraisal_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'section_order', name='uq_section_order'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_appraisal_section_template', 'appraisal_sections', ['template_id'], unique=False)
    op.create_index(op.f('ix_appraisal_sections_template_id'), 'appraisal_sections', ['template_id'], unique=False)
    op.create_table('department_goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('framework_id', sa.Integer(), nullable=False),
    sa.Column('parent_org_goal_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.String(length=10), nullable=True),
    sa.Column('measurement_type', sa.Enum('NUMERIC', 'PERCENTAGE', 'BOOLEAN', 'MILESTONE', name='goalmeasurementtype'), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('progress_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ON_TRACK', 'AT_RISK', 'BEHIND', 'COMPLETED', 'CANCELLED', name='goalstatus'), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['framework_id'], ['goal_frameworks.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['parent_org_goal_id'], ['organization_goals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_dept_goal_dept_status', 'department_goals', ['department_id', 'status'], unique=False)
    op.create_index('idx_dept_goal_parent', 'department_goals', ['parent_org_goal_id'], unique=False)
    op.create_index(op.f('ix_department_goals_department_id'), 'department_goals', ['department_id'], unique=False)
    op.create_table('succession_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('succession_plan_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('readiness', sa.String(length=30), nullable=False),
    sa.Column('readiness_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gap_assessment', sa.JSON(), nullable=True),
    sa.Column('development_plan', sa.Text(), nullable=True),
    sa.Column('is_primary_candidate', sa.Boolean(), nullable=True),
    sa.Column('priority_rank', sa.SmallInteger(), nullable=True),
    sa.Column('retention_risk', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['succession_plan_id'], ['succession_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('succession_plan_id', 'employee_id', name='uq_succession_candidate'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_succession_candidate_plan', 'succession_candidates', ['succession_plan_id', 'readiness'], unique=False)
    op.create_index(op.f('ix_succession_candidates_employee_id'), 'succession_candidates', ['employee_id'], unique=False)
    op.create_index(op.f('ix_succession_candidates_succession_plan_id'), 'succession_candidates', ['succession_plan_id'], unique=False)
    op.create_table('appraisal_calibrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('appraisal_cycle_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('conducted_date', sa.DateTime(), nullable=True),
    sa.Column('facilitator_id', sa.Integer(), nullable=False),
    sa.Column('target_distribution', sa.JSON(), nullable=True),
    sa.Column('actual_distribution', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('session_notes', sa.Text(), nullable=True),
    sa.Column('meeting_minutes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appraisal_cycle_id'], ['appraisal_cycles.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['facilitator_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_calibration_cycle_dept', 'appraisal_calibrations', ['appraisal_cycle_id', 'department_id'], unique=False)
    op.create_index(op.f('ix_appraisal_calibrations_appraisal_cycle_id'), 'appraisal_calibrations', ['appraisal_cycle_id'], unique=False)
    op.create_table('appraisal_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('RATING', 'TEXT', 'MULTI_CHOICE', 'GOAL_RATING', 'COMPETENCY_RATING', name='questiontype'), nullable=False),
    sa.Column('question_order', sa.SmallInteger(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('use_section_rating_scale', sa.Boolean(), nullable=True),
    sa.Column('custom_rating_scale_id', sa.Integer(), nullable=True),
    sa.Column('choices', sa.JSON(), nullable=True),
    sa.Column('allow_multiple_selection', sa.Boolean(), nullable=True),
    sa.Column('competency_id', sa.Integer(), nullable=True),
    sa.Column('auto_populate_goals', sa.Boolean(), nullable=True),
    sa.Column('guidance', sa.Text(), nullable=True),
    sa.Column('placeholder_text', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competency_frameworks.id'], ),
    sa.ForeignKeyConstraint(['custom_rating_scale_id'], ['rating_scales.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['appraisal_sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'question_order', name='uq_question_order'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_appraisal_questions_section_id'), 'appraisal_questions', ['section_id'], unique=False)
    op.create_table('appraisal_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('appraisal_cycle_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('rating_scale_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'SELF_IN_PROGRESS', 'SELF_SUBMITTED', 'MANAGER_IN_PROGRESS', 'MANAGER_SUBMITTED', 'CALIBRATION_PENDING', 'CALIBRATED', 'PUBLISHED', 'ACKNOWLEDGED', name='appraisalstatus'), nullable=True),
    sa.Column('self_goal_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('self_competency_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('self_overall_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('self_rating_label', sa.String(length=50), nullable=True),
    sa.Column('manager_goal_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('manager_competency_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('manager_overall_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('manager_rating_label', sa.String(length=50), nullable=True),
    sa.Column('final_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('final_rating_label', sa.String(length=50), nullable=True),
    sa.Column('calibrated_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('calibrated_by', sa.Integer(), nullable=True),
    sa.Column('calibrated_at', sa.DateTime(), nullable=True),
    sa.Column('calibration_notes', sa.Text(), nullable=True),
    sa.Column('self_appraisal_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('manager_review_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('published_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_by_employee', sa.Boolean(), nullable=True),
    sa.Column('employee_acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('employee_disagreement_reason', sa.Text(), nullable=True),
    sa.Column('has_360_feedback', sa.Boolean(), nullable=True),
    sa.Column('feedback_360_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('compensation_action_triggered', sa.Boolean(), nullable=True),
    sa.Column('promotion_recommended', sa.Boolean(), nullable=True),
    sa.Column('promotion_recommended_to_grade', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appraisal_cycle_id'], ['appraisal_cycles.id'], ),
    sa.ForeignKeyConstraint(['calibrated_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['published_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['rating_scale_id'], ['rating_scales.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['appraisal_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appraisal_cycle_id', 'employee_id', name='uq_appraisal_per_cycle'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_appraisal_record_cycle_status', 'appraisal_records', ['appraisal_cycle_id', 'status'], unique=False)
    op.create_index('idx_appraisal_record_emp_cycle_status', 'appraisal_records', ['employee_id', 'appraisal_cycle_id', 'status'], unique=False)
    op.create_index('idx_appraisal_record_manager', 'appraisal_records', ['manager_id', 'status'], unique=False)
    op.create_index(op.f('ix_appraisal_records_appraisal_cycle_id'), 'appraisal_records', ['appraisal_cycle_id'], unique=False)
    op.create_index(op.f('ix_appraisal_records_employee_id'), 'appraisal_records', ['employee_id'], unique=False)
    op.create_index(op.f('ix_appraisal_records_status'), 'appraisal_records', ['status'], unique=False)
    op.create_table('bell_curve_distributions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('appraisal_cycle_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('rating_label', sa.String(length=100), nullable=False),
    sa.Column('target_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=True),
    sa.Column('actual_count', sa.Integer(), nullable=True),
    sa.Column('actual_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('variance', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_within_target', sa.Boolean(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appraisal_cycle_id'], ['appraisal_cycles.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_bell_curve_cycle_dept', 'bell_curve_distributions', ['appraisal_cycle_id', 'department_id'], unique=False)
    op.create_index(op.f('ix_bell_curve_distributions_appraisal_cycle_id'), 'bell_curve_distributions', ['appraisal_cycle_id'], unique=False)
    op.create_table('employee_goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('framework_id', sa.Integer(), nullable=False),
    sa.Column('parent_dept_goal_id', sa.Integer(), nullable=True),
    sa.Column('parent_org_goal_id', sa.Integer(), nullable=True),
    sa.Column('appraisal_cycle_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_specific', sa.Boolean(), nullable=True),
    sa.Column('is_measurable', sa.Boolean(), nullable=True),
    sa.Column('is_achievable', sa.Boolean(), nullable=True),
    sa.Column('is_relevant', sa.Boolean(), nullable=True),
    sa.Column('is_time_bound', sa.Boolean(), nullable=True),
    sa.Column('objective_key', sa.String(length=20), nullable=True),
    sa.Column('is_key_result', sa.Boolean(), nullable=True),
    sa.Column('parent_objective_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('measurement_type', sa.Enum('NUMERIC', 'PERCENTAGE', 'BOOLEAN', 'MILESTONE', name='goalmeasurementtype'), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('baseline_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ON_TRACK', 'AT_RISK', 'BEHIND', 'COMPLETED', 'CANCELLED', name='goalstatus'), nullable=True),
    sa.Column('progress_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('manager_comment', sa.Text(), nullable=True),
    sa.Column('achieved_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('achievement_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('goal_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_stretch_goal', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appraisal_cycle_id'], ['appraisal_cycles.id'], ),
    sa.ForeignKeyConstraint(['approved_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['framework_id'], ['goal_frameworks.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['parent_dept_goal_id'], ['department_goals.id'], ),
    sa.ForeignKeyConstraint(['parent_objective_id'], ['employee_goals.id'], ),
    sa.ForeignKeyConstraint(['parent_org_goal_id'], ['organization_goals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_emp_goal_cycle', 'employee_goals', ['appraisal_cycle_id', 'employee_id'], unique=False)
    op.create_index('idx_emp_goal_emp_end_status', 'employee_goals', ['employee_id', 'end_date', 'status'], unique=False)
    op.create_index('idx_emp_goal_emp_status', 'employee_goals', ['employee_id', 'status'], unique=False)
    op.create_index('idx_emp_goal_parent_dept', 'employee_goals', ['parent_dept_goal_id'], unique=False)
    op.create_index(op.f('ix_employee_goals_employee_id'), 'employee_goals', ['employee_id'], unique=False)
    op.create_table('one_on_one_meetings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.SmallInteger(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('meeting_type', sa.String(length=30), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('recurrence_pattern', sa.String(length=50), nullable=True),
    sa.Column('recurrence_end_date', sa.Date(), nullable=True),
    sa.Column('series_id', app.models.organization.GUID(), nullable=True),
    sa.Column('pre_meeting_notes', sa.Text(), nullable=True),
    sa.Column('meeting_notes', sa.Text(), nullable=True),
    sa.Column('key_decisions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_reason', sa.String(length=255), nullable=True),
    sa.Column('appraisal_cycle_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appraisal_cycle_id'], ['appraisal_cycles.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_one_on_one_manager_emp', 'one_on_one_meetings', ['manager_id', 'employee_id', 'scheduled_date'], unique=False)
    op.create_index(op.f('ix_one_on_one_meetings_employee_id'), 'one_on_one_meetings', ['employee_id'], unique=False)
    op.create_index(op.f('ix_one_on_one_meetings_manager_id'), 'one_on_one_meetings', ['manager_id'], unique=False)
    op.create_table('performance_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('appraisal_cycle_id', sa.Integer(), nullable=True),
    sa.Column('metric_type', sa.String(length=100), nullable=False),
    sa.Column('metric_scope', sa.String(length=30), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('previous_value', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('change_percentage', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('period_label', sa.String(length=50), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appraisal_cycle_id'], ['appraisal_cycles.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_perf_metrics_org_cycle', 'performance_metrics', ['organization_id', 'appraisal_cycle_id', 'metric_type'], unique=False)
    op.create_index('idx_perf_metrics_scope', 'performance_metrics', ['metric_scope', 'scope_id'], unique=False)
    op.create_table('performance_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('appraisal_cycle_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.Enum('CYCLE_STARTED', 'SELF_APPRAISAL_DUE', 'SELF_APPRAISAL_REMINDER', 'MANAGER_REVIEW_DUE', 'FEEDBACK_REQUEST', 'FEEDBACK_REMINDER', 'GOAL_DUE', 'APPRAISAL_PUBLISHED', 'PIP_CREATED', 'ONE_ON_ONE_REMINDER', 'CALIBRATION_SCHEDULED', name='notificationtype'), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('delivery_status', sa.String(length=30), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('retry_count', sa.SmallInteger(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appraisal_cycle_id'], ['appraisal_cycles.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['notification_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_perf_notif_cycle', 'performance_notifications', ['appraisal_cycle_id', 'notification_type'], unique=False)
    op.create_index('idx_perf_notif_recipient', 'performance_notifications', ['recipient_id', 'is_sent', 'notification_type'], unique=False)
    op.create_index(op.f('ix_performance_notifications_recipient_id'), 'performance_notifications', ['recipient_id'], unique=False)
    op.create_table('skills_gap_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('appraisal_cycle_id', sa.Integer(), nullable=True),
    sa.Column('conducted_by', sa.Integer(), nullable=False),
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('gap_details', sa.JSON(), nullable=False),
    sa.Column('overall_readiness_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('critical_gaps_count', sa.SmallInteger(), nullable=True),
    sa.Column('recommended_training', sa.JSON(), nullable=True),
    sa.Column('development_priority', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appraisal_cycle_id'], ['appraisal_cycles.id'], ),
    sa.ForeignKeyConstraint(['conducted_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_skills_gap_employee_cycle', 'skills_gap_analyses', ['employee_id', 'appraisal_cycle_id'], unique=False)
    op.create_index(op.f('ix_skills_gap_analyses_employee_id'), 'skills_gap_analyses', ['employee_id'], unique=False)
    op.create_table('talent_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('appraisal_cycle_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('facilitator_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('session_minutes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appraisal_cycle_id'], ['appraisal_cycles.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['facilitator_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_talent_review_org_cycle', 'talent_reviews', ['organization_id', 'appraisal_cycle_id'], unique=False)
    op.create_index(op.f('ix_talent_reviews_organization_id'), 'talent_reviews', ['organization_id'], unique=False)
    op.create_table('appraisal_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('appraisal_record_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('respondent_type', sa.String(length=20), nullable=False),
    sa.Column('respondent_id', sa.Integer(), nullable=False),
    sa.Column('rating_value', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rating_label', sa.String(length=100), nullable=True),
    sa.Column('text_answer', sa.Text(), nullable=True),
    sa.Column('selected_choices', sa.JSON(), nullable=True),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('goal_achievement_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('competency_id', sa.Integer(), nullable=True),
    sa.Column('weight_applied', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weighted_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appraisal_record_id'], ['appraisal_records.id'], ),
    sa.ForeignKeyConstraint(['competency_id'], ['competency_frameworks.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['employee_goals.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['appraisal_questions.id'], ),
    sa.ForeignKeyConstraint(['respondent_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appraisal_record_id', 'question_id', 'respondent_type', name='uq_appraisal_answer'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_appraisal_answer_record', 'appraisal_answers', ['appraisal_record_id', 'respondent_type'], unique=False)
    op.create_index(op.f('ix_appraisal_answers_appraisal_record_id'), 'appraisal_answers', ['appraisal_record_id'], unique=False)
    op.create_table('calibration_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calibration_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('attended', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['calibration_id'], ['appraisal_calibrations.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calibration_id', 'participant_id', name='uq_calibration_participant')
    )
    op.create_index(op.f('ix_calibration_participants_calibration_id'), 'calibration_participants', ['calibration_id'], unique=False)
    op.create_table('compensation_integrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('appraisal_record_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('appraisal_cycle_id', sa.Integer(), nullable=False),
    sa.Column('final_rating_label', sa.String(length=100), nullable=True),
    sa.Column('final_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('merit_increase_recommended', sa.Boolean(), nullable=True),
    sa.Column('merit_increase_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bonus_recommended', sa.Boolean(), nullable=True),
    sa.Column('bonus_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bonus_type', sa.String(length=50), nullable=True),
    sa.Column('promotion_recommended', sa.Boolean(), nullable=True),
    sa.Column('recommended_grade', sa.String(length=50), nullable=True),
    sa.Column('recommended_role_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('submitted_to_compensation_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('compensation_action_id', sa.Integer(), nullable=True),
    sa.Column('action_effective_date', sa.Date(), nullable=True),
    sa.Column('action_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appraisal_cycle_id'], ['appraisal_cycles.id'], ),
    sa.ForeignKeyConstraint(['appraisal_record_id'], ['appraisal_records.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['recommended_role_id'], ['job_titles.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appraisal_record_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_comp_integration_cycle', 'compensation_integrations', ['appraisal_cycle_id', 'status'], unique=False)
    op.create_index(op.f('ix_compensation_integrations_employee_id'), 'compensation_integrations', ['employee_id'], unique=False)
    op.create_table('continuous_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('giver_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('feedback_type', sa.String(length=30), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=True),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('is_visible_to_manager', sa.Boolean(), nullable=True),
    sa.Column('is_shared_with_hr', sa.Boolean(), nullable=True),
    sa.Column('receiver_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('receiver_acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('receiver_reaction', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competency_frameworks.id'], ),
    sa.ForeignKeyConstraint(['giver_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['employee_goals.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_continuous_feedback_giver', 'continuous_feedback', ['giver_id'], unique=False)
    op.create_index('idx_continuous_feedback_receiver', 'continuous_feedback', ['receiver_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_continuous_feedback_giver_id'), 'continuous_feedback', ['giver_id'], unique=False)
    op.create_index(op.f('ix_continuous_feedback_receiver_id'), 'continuous_feedback', ['receiver_id'], unique=False)
    op.create_table('employee_competencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('appraisal_cycle_id', sa.Integer(), nullable=True),
    sa.Column('appraisal_record_id', sa.Integer(), nullable=True),
    sa.Column('self_rating', sa.SmallInteger(), nullable=True),
    sa.Column('manager_rating', sa.SmallInteger(), nullable=True),
    sa.Column('final_rating', sa.SmallInteger(), nullable=True),
    sa.Column('feedback_360_rating', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('required_level', sa.SmallInteger(), nullable=True),
    sa.Column('gap', sa.SmallInteger(), nullable=True),
    sa.Column('self_comments', sa.Text(), nullable=True),
    sa.Column('manager_comments', sa.Text(), nullable=True),
    sa.Column('assessed_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appraisal_cycle_id'], ['appraisal_cycles.id'], ),
    sa.ForeignKeyConstraint(['appraisal_record_id'], ['appraisal_records.id'], ),
    sa.ForeignKeyConstraint(['competency_id'], ['competency_frameworks.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'competency_id', 'appraisal_cycle_id', name='uq_employee_competency_cycle'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_emp_competency_cycle', 'employee_competencies', ['appraisal_cycle_id', 'employee_id'], unique=False)
    op.create_index(op.f('ix_employee_competencies_employee_id'), 'employee_competencies', ['employee_id'], unique=False)
    op.create_table('feedback_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('appraisal_cycle_id', sa.Integer(), nullable=False),
    sa.Column('appraisal_record_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('initiated_by', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'EXPIRED', name='feedbackrequeststatus'), nullable=True),
    sa.Column('min_peer_responses', sa.SmallInteger(), nullable=True),
    sa.Column('min_subordinate_responses', sa.SmallInteger(), nullable=True),
    sa.Column('avg_rating', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('response_summary', sa.JSON(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appraisal_cycle_id'], ['appraisal_cycles.id'], ),
    sa.ForeignKeyConstraint(['appraisal_record_id'], ['appraisal_records.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appraisal_cycle_id', 'employee_id', name='uq_feedback_request_cycle'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_feedback_request_employee', 'feedback_requests', ['employee_id', 'status'], unique=False)
    op.create_index(op.f('ix_feedback_requests_appraisal_cycle_id'), 'feedback_requests', ['appraisal_cycle_id'], unique=False)
    op.create_index(op.f('ix_feedback_requests_employee_id'), 'feedback_requests', ['employee_id'], unique=False)
    op.create_table('goal_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('employee_goal_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('progress_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ON_TRACK', 'AT_RISK', 'BEHIND', 'COMPLETED', 'CANCELLED', name='goalstatus'), nullable=False),
    sa.Column('update_notes', sa.Text(), nullable=True),
    sa.Column('blockers', sa.Text(), nullable=True),
    sa.Column('next_steps', sa.Text(), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('manager_comment', sa.Text(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_goal_id'], ['employee_goals.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_goal_progress_goal_date', 'goal_progress', ['employee_goal_id', 'check_in_date'], unique=False)
    op.create_index(op.f('ix_goal_progress_employee_goal_id'), 'goal_progress', ['employee_goal_id'], unique=False)
    op.create_table('manager_appraisals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('appraisal_record_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('performance_summary', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('areas_for_improvement', sa.Text(), nullable=True),
    sa.Column('development_plan', sa.Text(), nullable=True),
    sa.Column('promotion_recommendation', sa.Text(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('is_submitted', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('last_saved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appraisal_record_id'], ['appraisal_records.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appraisal_record_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_manager_appraisal_manager', 'manager_appraisals', ['manager_id'], unique=False)
    op.create_index(op.f('ix_manager_appraisals_manager_id'), 'manager_appraisals', ['manager_id'], unique=False)
    op.create_table('one_on_one_agenda_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=False),
    sa.Column('item_order', sa.SmallInteger(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('carried_from_meeting_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['carried_from_meeting_id'], ['one_on_one_meetings.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['one_on_one_meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agenda_item_meeting', 'one_on_one_agenda_items', ['meeting_id', 'item_type'], unique=False)
    op.create_index(op.f('ix_one_on_one_agenda_items_meeting_id'), 'one_on_one_agenda_items', ['meeting_id'], unique=False)
    op.create_table('performance_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('note_type', sa.String(length=30), nullable=False),
    sa.Column('note_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('is_shared_with_employee', sa.Boolean(), nullable=True),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('competency_id', sa.Integer(), nullable=True),
    sa.Column('one_on_one_id', sa.Integer(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competency_frameworks.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['employee_goals.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['one_on_one_id'], ['one_on_one_meetings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_perf_note_emp_date', 'performance_notes', ['employee_id', 'note_date'], unique=False)
    op.create_index('idx_perf_note_manager', 'performance_notes', ['manager_id', 'note_date'], unique=False)
    op.create_index(op.f('ix_performance_notes_employee_id'), 'performance_notes', ['employee_id'], unique=False)
    op.create_index(op.f('ix_performance_notes_manager_id'), 'performance_notes', ['manager_id'], unique=False)
    op.create_table('pii_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('hr_owner_id', sa.Integer(), nullable=True),
    sa.Column('appraisal_record_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('review_frequency', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ON_TRACK', 'AT_RISK', 'COMPLETED_SUCCESS', 'COMPLETED_FAILURE', 'WITHDRAWN', name='pipstatus'), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by', sa.Integer(), nullable=True),
    sa.Column('employee_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('employee_acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('employee_comments', sa.Text(), nullable=True),
    sa.Column('hr_approved', sa.Boolean(), nullable=True),
    sa.Column('hr_approved_at', sa.DateTime(), nullable=True),
    sa.Column('hr_approval_notes', sa.Text(), nullable=True),
    sa.Column('support_resources', sa.Text(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appraisal_record_id'], ['appraisal_records.id'], ),
    sa.ForeignKeyConstraint(['closed_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['hr_owner_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_pip_employee_status', 'pii_plans', ['employee_id', 'status'], unique=False)
    op.create_index('idx_pip_plan_manager', 'pii_plans', ['manager_id', 'status'], unique=False)
    op.create_index(op.f('ix_pii_plans_employee_id'), 'pii_plans', ['employee_id'], unique=False)
    op.create_table('self_appraisals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('appraisal_record_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('achievements_summary', sa.Text(), nullable=True),
    sa.Column('challenges_faced', sa.Text(), nullable=True),
    sa.Column('learning_development', sa.Text(), nullable=True),
    sa.Column('career_aspirations', sa.Text(), nullable=True),
    sa.Column('support_needed', sa.Text(), nullable=True),
    sa.Column('is_submitted', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('last_saved_at', sa.DateTime(), nullable=True),
    sa.Column('draft_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appraisal_record_id'], ['appraisal_records.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appraisal_record_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_self_appraisal_employee', 'self_appraisals', ['employee_id'], unique=False)
    op.create_index(op.f('ix_self_appraisals_employee_id'), 'self_appraisals', ['employee_id'], unique=False)
    op.create_table('talent_review_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('talent_review_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('performance_rating', sa.SmallInteger(), nullable=True),
    sa.Column('potential_rating', sa.SmallInteger(), nullable=True),
    sa.Column('nine_box_position', sa.Enum('LOW_LOW', 'LOW_MED', 'LOW_HIGH', 'MED_LOW', 'MED_MED', 'MED_HIGH', 'HIGH_LOW', 'HIGH_MED', 'HIGH_HIGH', name='nineboxposition'), nullable=True),
    sa.Column('talent_category', sa.Enum('HIGH_POTENTIAL', 'HIGH_PERFORMER', 'CORE_CONTRIBUTOR', 'NEEDS_IMPROVEMENT', 'NEW_HIRE', name='talentcategory'), nullable=True),
    sa.Column('flight_risk', sa.String(length=20), nullable=True),
    sa.Column('flight_risk_reason', sa.Text(), nullable=True),
    sa.Column('readiness_for_promotion', sa.String(length=20), nullable=True),
    sa.Column('development_needs', sa.Text(), nullable=True),
    sa.Column('retention_priority', sa.String(length=20), nullable=True),
    sa.Column('reviewer_comments', sa.Text(), nullable=True),
    sa.Column('is_key_talent', sa.Boolean(), nullable=True),
    sa.Column('is_succession_candidate', sa.Boolean(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['talent_review_id'], ['talent_reviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('talent_review_id', 'employee_id', name='uq_talent_review_participant')
    )
    op.create_index('idx_talent_review_participant_nine_box', 'talent_review_participants', ['talent_review_id', 'nine_box_position'], unique=False)
    op.create_index(op.f('ix_talent_review_participants_employee_id'), 'talent_review_participants', ['employee_id'], unique=False)
    op.create_index(op.f('ix_talent_review_participants_talent_review_id'), 'talent_review_participants', ['talent_review_id'], unique=False)
    op.create_table('feedback_providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('feedback_request_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('provider_type', sa.Enum('SELF', 'PEER', 'SUBORDINATE', 'SUPERVISOR', 'EXTERNAL', name='feedbackprovidertype'), nullable=False),
    sa.Column('approved_by_manager', sa.Boolean(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('invite_sent_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_sent_count', sa.SmallInteger(), nullable=True),
    sa.Column('last_reminder_sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'EXPIRED', name='feedbackrequeststatus'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_request_id'], ['feedback_requests.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feedback_request_id', 'provider_id', name='uq_feedback_provider'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_feedback_provider_provider', 'feedback_providers', ['provider_id', 'status'], unique=False)
    op.create_index(op.f('ix_feedback_providers_feedback_request_id'), 'feedback_providers', ['feedback_request_id'], unique=False)
    op.create_table('pii_objectives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('pip_plan_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('success_criteria', sa.Text(), nullable=False),
    sa.Column('measurement_type', sa.Enum('NUMERIC', 'PERCENTAGE', 'BOOLEAN', 'MILESTONE', name='goalmeasurementtype'), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ON_TRACK', 'AT_RISK', 'BEHIND', 'COMPLETED', 'CANCELLED', name='goalstatus'), nullable=True),
    sa.Column('achievement_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pip_plan_id'], ['pii_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_pip_objective_plan', 'pii_objectives', ['pip_plan_id', 'status'], unique=False)
    op.create_index(op.f('ix_pii_objectives_pip_plan_id'), 'pii_objectives', ['pip_plan_id'], unique=False)
    op.create_table('pii_progress_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('pip_plan_id', sa.Integer(), nullable=False),
    sa.Column('logged_by', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('objective_updates', sa.JSON(), nullable=False),
    sa.Column('overall_status', sa.Enum('DRAFT', 'ACTIVE', 'ON_TRACK', 'AT_RISK', 'COMPLETED_SUCCESS', 'COMPLETED_FAILURE', 'WITHDRAWN', name='pipstatus'), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('manager_recommendations', sa.Text(), nullable=True),
    sa.Column('support_given', sa.Text(), nullable=True),
    sa.Column('employee_response', sa.Text(), nullable=True),
    sa.Column('employee_responded_at', sa.DateTime(), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('meeting_held', sa.Boolean(), nullable=True),
    sa.Column('meeting_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['logged_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['pip_plan_id'], ['pii_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_pip_progress_plan_date', 'pii_progress_logs', ['pip_plan_id', 'log_date'], unique=False)
    op.create_index(op.f('ix_pii_progress_logs_pip_plan_id'), 'pii_progress_logs', ['pip_plan_id'], unique=False)
    op.create_table('feedback_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('feedback_provider_id', sa.Integer(), nullable=False),
    sa.Column('feedback_request_id', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('overall_comments', sa.Text(), nullable=True),
    sa.Column('strengths_observed', sa.Text(), nullable=True),
    sa.Column('development_suggestions', sa.Text(), nullable=True),
    sa.Column('overall_rating', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_submitted', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('anon_token', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_provider_id'], ['feedback_providers.id'], ),
    sa.ForeignKeyConstraint(['feedback_request_id'], ['feedback_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anon_token'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_feedback_response_request', 'feedback_responses', ['feedback_request_id'], unique=False)
    op.create_index(op.f('ix_feedback_responses_feedback_provider_id'), 'feedback_responses', ['feedback_provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_responses_feedback_provider_id'), table_name='feedback_responses')
    op.drop_index('idx_feedback_response_request', table_name='feedback_responses')
    op.drop_table('feedback_responses')
    op.drop_index(op.f('ix_pii_progress_logs_pip_plan_id'), table_name='pii_progress_logs')
    op.drop_index('idx_pip_progress_plan_date', table_name='pii_progress_logs')
    op.drop_table('pii_progress_logs')
    op.drop_index(op.f('ix_pii_objectives_pip_plan_id'), table_name='pii_objectives')
    op.drop_index('idx_pip_objective_plan', table_name='pii_objectives')
    op.drop_table('pii_objectives')
    op.drop_index(op.f('ix_feedback_providers_feedback_request_id'), table_name='feedback_providers')
    op.drop_index('idx_feedback_provider_provider', table_name='feedback_providers')
    op.drop_table('feedback_providers')
    op.drop_index(op.f('ix_talent_review_participants_talent_review_id'), table_name='talent_review_participants')
    op.drop_index(op.f('ix_talent_review_participants_employee_id'), table_name='talent_review_participants')
    op.drop_index('idx_talent_review_participant_nine_box', table_name='talent_review_participants')
    op.drop_table('talent_review_participants')
    op.drop_index(op.f('ix_self_appraisals_employee_id'), table_name='self_appraisals')
    op.drop_index('idx_self_appraisal_employee', table_name='self_appraisals')
    op.drop_table('self_appraisals')
    op.drop_index(op.f('ix_pii_plans_employee_id'), table_name='pii_plans')
    op.drop_index('idx_pip_plan_manager', table_name='pii_plans')
    op.drop_index('idx_pip_employee_status', table_name='pii_plans')
    op.drop_table('pii_plans')
    op.drop_index(op.f('ix_performance_notes_manager_id'), table_name='performance_notes')
    op.drop_index(op.f('ix_performance_notes_employee_id'), table_name='performance_notes')
    op.drop_index('idx_perf_note_manager', table_name='performance_notes')
    op.drop_index('idx_perf_note_emp_date', table_name='performance_notes')
    op.drop_table('performance_notes')
    op.drop_index(op.f('ix_one_on_one_agenda_items_meeting_id'), table_name='one_on_one_agenda_items')
    op.drop_index('idx_agenda_item_meeting', table_name='one_on_one_agenda_items')
    op.drop_table('one_on_one_agenda_items')
    op.drop_index(op.f('ix_manager_appraisals_manager_id'), table_name='manager_appraisals')
    op.drop_index('idx_manager_appraisal_manager', table_name='manager_appraisals')
    op.drop_table('manager_appraisals')
    op.drop_index(op.f('ix_goal_progress_employee_goal_id'), table_name='goal_progress')
    op.drop_index('idx_goal_progress_goal_date', table_name='goal_progress')
    op.drop_table('goal_progress')
    op.drop_index(op.f('ix_feedback_requests_employee_id'), table_name='feedback_requests')
    op.drop_index(op.f('ix_feedback_requests_appraisal_cycle_id'), table_name='feedback_requests')
    op.drop_index('idx_feedback_request_employee', table_name='feedback_requests')
    op.drop_table('feedback_requests')
    op.drop_index(op.f('ix_employee_competencies_employee_id'), table_name='employee_competencies')
    op.drop_index('idx_emp_competency_cycle', table_name='employee_competencies')
    op.drop_table('employee_competencies')
    op.drop_index(op.f('ix_continuous_feedback_receiver_id'), table_name='continuous_feedback')
    op.drop_index(op.f('ix_continuous_feedback_giver_id'), table_name='continuous_feedback')
    op.drop_index('idx_continuous_feedback_receiver', table_name='continuous_feedback')
    op.drop_index('idx_continuous_feedback_giver', table_name='continuous_feedback')
    op.drop_table('continuous_feedback')
    op.drop_index(op.f('ix_compensation_integrations_employee_id'), table_name='compensation_integrations')
    op.drop_index('idx_comp_integration_cycle', table_name='compensation_integrations')
    op.drop_table('compensation_integrations')
    op.drop_index(op.f('ix_calibration_participants_calibration_id'), table_name='calibration_participants')
    op.drop_table('calibration_participants')
    op.drop_index(op.f('ix_appraisal_answers_appraisal_record_id'), table_name='appraisal_answers')
    op.drop_index('idx_appraisal_answer_record', table_name='appraisal_answers')
    op.drop_table('appraisal_answers')
    op.drop_index(op.f('ix_talent_reviews_organization_id'), table_name='talent_reviews')
    op.drop_index('idx_talent_review_org_cycle', table_name='talent_reviews')
    op.drop_table('talent_reviews')
    op.drop_index(op.f('ix_skills_gap_analyses_employee_id'), table_name='skills_gap_analyses')
    op.drop_index('idx_skills_gap_employee_cycle', table_name='skills_gap_analyses')
    op.drop_table('skills_gap_analyses')
    op.drop_index(op.f('ix_performance_notifications_recipient_id'), table_name='performance_notifications')
    op.drop_index('idx_perf_notif_recipient', table_name='performance_notifications')
    op.drop_index('idx_perf_notif_cycle', table_name='performance_notifications')
    op.drop_table('performance_notifications')
    op.drop_index('idx_perf_metrics_scope', table_name='performance_metrics')
    op.drop_index('idx_perf_metrics_org_cycle', table_name='performance_metrics')
    op.drop_table('performance_metrics')
    op.drop_index(op.f('ix_one_on_one_meetings_manager_id'), table_name='one_on_one_meetings')
    op.drop_index(op.f('ix_one_on_one_meetings_employee_id'), table_name='one_on_one_meetings')
    op.drop_index('idx_one_on_one_manager_emp', table_name='one_on_one_meetings')
    op.drop_table('one_on_one_meetings')
    op.drop_index(op.f('ix_employee_goals_employee_id'), table_name='employee_goals')
    op.drop_index('idx_emp_goal_parent_dept', table_name='employee_goals')
    op.drop_index('idx_emp_goal_emp_status', table_name='employee_goals')
    op.drop_index('idx_emp_goal_emp_end_status', table_name='employee_goals')
    op.drop_index('idx_emp_goal_cycle', table_name='employee_goals')
    op.drop_table('employee_goals')
    op.drop_index(op.f('ix_bell_curve_distributions_appraisal_cycle_id'), table_name='bell_curve_distributions')
    op.drop_index('idx_bell_curve_cycle_dept', table_name='bell_curve_distributions')
    op.drop_table('bell_curve_distributions')
    op.drop_index(op.f('ix_appraisal_records_status'), table_name='appraisal_records')
    op.drop_index(op.f('ix_appraisal_records_employee_id'), table_name='appraisal_records')
    op.drop_index(op.f('ix_appraisal_records_appraisal_cycle_id'), table_name='appraisal_records')
    op.drop_index('idx_appraisal_record_manager', table_name='appraisal_records')
    op.drop_index('idx_appraisal_record_emp_cycle_status', table_name='appraisal_records')
    op.drop_index('idx_appraisal_record_cycle_status', table_name='appraisal_records')
    op.drop_table('appraisal_records')
    op.drop_index(op.f('ix_appraisal_questions_section_id'), table_name='appraisal_questions')
    op.drop_table('appraisal_questions')
    op.drop_index(op.f('ix_appraisal_calibrations_appraisal_cycle_id'), table_name='appraisal_calibrations')
    op.drop_index('idx_calibration_cycle_dept', table_name='appraisal_calibrations')
    op.drop_table('appraisal_calibrations')
    op.drop_index(op.f('ix_succession_candidates_succession_plan_id'), table_name='succession_candidates')
    op.drop_index(op.f('ix_succession_candidates_employee_id'), table_name='succession_candidates')
    op.drop_index('idx_succession_candidate_plan', table_name='succession_candidates')
    op.drop_table('succession_candidates')
    op.drop_index(op.f('ix_department_goals_department_id'), table_name='department_goals')
    op.drop_index('idx_dept_goal_parent', table_name='department_goals')
    op.drop_index('idx_dept_goal_dept_status', table_name='department_goals')
    op.drop_table('department_goals')
    op.drop_index(op.f('ix_appraisal_sections_template_id'), table_name='appraisal_sections')
    op.drop_index('idx_appraisal_section_template', table_name='appraisal_sections')
    op.drop_table('appraisal_sections')
    op.drop_index(op.f('ix_appraisal_cycles_organization_id'), table_name='appraisal_cycles')
    op.drop_index('idx_appraisal_cycle_org_status', table_name='appraisal_cycles')
    op.drop_table('appraisal_cycles')
    op.drop_index(op.f('ix_succession_plans_organization_id'), table_name='succession_plans')
    op.drop_index('idx_succession_plan_dept', table_name='succession_plans')
    op.drop_table('succession_plans')
    op.drop_index(op.f('ix_organization_goals_organization_id'), table_name='organization_goals')
    op.drop_index('idx_org_goal_status_year', table_name='organization_goals')
    op.drop_table('organization_goals')
    op.drop_index(op.f('ix_feedback_questions_organization_id'), table_name='feedback_questions')
    op.drop_index('idx_feedback_question_org', table_name='feedback_questions')
    op.drop_table('feedback_questions')
    op.drop_index(op.f('ix_competency_mappings_competency_id'), table_name='competency_mappings')
    op.drop_index('idx_competency_mapping_role', table_name='competency_mappings')
    op.drop_index('idx_competency_mapping_dept', table_name='competency_mappings')
    op.drop_table('competency_mappings')
    op.drop_index(op.f('ix_appraisal_templates_organization_id'), table_name='appraisal_templates')
    op.drop_index('idx_appraisal_template_org', table_name='appraisal_templates')
    op.drop_table('appraisal_templates')
    op.drop_index(op.f('ix_rating_scales_organization_id'), table_name='rating_scales')
    op.drop_table('rating_scales')
    op.drop_index(op.f('ix_notification_templates_organization_id'), table_name='notification_templates')
    op.drop_table('notification_templates')
    op.drop_index(op.f('ix_goal_frameworks_organization_id'), table_name='goal_frameworks')
    op.drop_index('idx_goal_framework_org', table_name='goal_frameworks')
    op.drop_table('goal_frameworks')
    op.drop_index('idx_goal_align_parent', table_name='goal_alignments')
    op.drop_index('idx_goal_align_child', table_name='goal_alignments')
    op.drop_table('goal_alignments')
    op.drop_index(op.f('ix_competency_frameworks_organization_id'), table_name='competency_frameworks')
    op.drop_index('idx_competency_org_active', table_name='competency_frameworks')
    op.drop_table('competency_frameworks')
    # ### end Alembic commands ###
