"""Add verification_notes to employee_docs

Revision ID: 4b90c952cb74
Revises: ca07399a2d9c
Create Date: 2026-01-11 16:40:07.938886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b90c952cb74'
down_revision: Union[str, Sequence[str], None] = 'ca07399a2d9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_documents', sa.Column('verification_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_documents', 'verification_notes')
    # ### end Alembic commands ###
