"""Add industry templates and quick setup tracking

Revision ID: 52b515439e99
Revises: 96aa4bfa9750
Create Date: 2026-05-03 00:31:12.964889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.organization


# revision identifiers, used by Alembic.
revision: str = '52b515439e99'
down_revision: Union[str, Sequence[str], None] = '96aa4bfa9750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_country_holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holiday_name', sa.String(length=200), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('holiday_type', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_country_holidays_country'), 'master_country_holidays', ['country'], unique=False)
    op.create_index(op.f('ix_master_country_holidays_id'), 'master_country_holidays', ['id'], unique=False)
    op.create_table('industry_attendance_policy_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.Column('policy_name', sa.String(length=150), nullable=False),
    sa.Column('working_days_per_week', sa.Integer(), nullable=True),
    sa.Column('working_hours_per_day', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('late_arrival_grace', sa.Integer(), nullable=True),
    sa.Column('early_departure_grace', sa.Integer(), nullable=True),
    sa.Column('overtime_enabled', sa.Boolean(), nullable=True),
    sa.Column('regularization_allowed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_attendance_policy_templates_id'), 'industry_attendance_policy_templates', ['id'], unique=False)
    op.create_table('industry_department_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.Column('department_code', sa.String(length=50), nullable=False),
    sa.Column('department_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_department_templates_id'), 'industry_department_templates', ['id'], unique=False)
    op.create_table('industry_job_title_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.Column('title_code', sa.String(length=50), nullable=False),
    sa.Column('title_name', sa.String(length=150), nullable=False),
    sa.Column('job_level', sa.String(length=50), nullable=True),
    sa.Column('job_family', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('qualifications', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_job_title_templates_id'), 'industry_job_title_templates', ['id'], unique=False)
    op.create_table('industry_role_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.Column('role_code', sa.String(length=100), nullable=False),
    sa.Column('role_name', sa.String(length=150), nullable=False),
    sa.Column('role_description', sa.Text(), nullable=True),
    sa.Column('role_level', sa.Integer(), nullable=True),
    sa.Column('scope', sa.String(length=50), nullable=True),
    sa.Column('color_code', sa.String(length=20), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('permission_codes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_role_templates_id'), 'industry_role_templates', ['id'], unique=False)
    op.create_table('industry_shift_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.Column('shift_code', sa.String(length=50), nullable=False),
    sa.Column('shift_name', sa.String(length=150), nullable=False),
    sa.Column('shift_type', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('work_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('break_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('has_break', sa.Boolean(), nullable=True),
    sa.Column('late_arrival_grace_minutes', sa.Integer(), nullable=True),
    sa.Column('early_departure_grace_minutes', sa.Integer(), nullable=True),
    sa.Column('week_off_days', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_shift_templates_id'), 'industry_shift_templates', ['id'], unique=False)
    op.create_table('quick_setup_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='quicksetupstatus'), nullable=False),
    sa.Column('selections', sa.JSON(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quick_setup_jobs_id'), 'quick_setup_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_quick_setup_jobs_organization_id'), 'quick_setup_jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_quick_setup_jobs_uuid'), 'quick_setup_jobs', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quick_setup_jobs_uuid'), table_name='quick_setup_jobs')
    op.drop_index(op.f('ix_quick_setup_jobs_organization_id'), table_name='quick_setup_jobs')
    op.drop_index(op.f('ix_quick_setup_jobs_id'), table_name='quick_setup_jobs')
    op.drop_table('quick_setup_jobs')
    op.drop_index(op.f('ix_industry_shift_templates_id'), table_name='industry_shift_templates')
    op.drop_table('industry_shift_templates')
    op.drop_index(op.f('ix_industry_role_templates_id'), table_name='industry_role_templates')
    op.drop_table('industry_role_templates')
    op.drop_index(op.f('ix_industry_job_title_templates_id'), table_name='industry_job_title_templates')
    op.drop_table('industry_job_title_templates')
    op.drop_index(op.f('ix_industry_department_templates_id'), table_name='industry_department_templates')
    op.drop_table('industry_department_templates')
    op.drop_index(op.f('ix_industry_attendance_policy_templates_id'), table_name='industry_attendance_policy_templates')
    op.drop_table('industry_attendance_policy_templates')
    op.drop_index(op.f('ix_master_country_holidays_id'), table_name='master_country_holidays')
    op.drop_index(op.f('ix_master_country_holidays_country'), table_name='master_country_holidays')
    op.drop_table('master_country_holidays')
    # ### end Alembic commands ###
