"""Add role_type_id to roles table

Revision ID: 582e583e3461
Revises: 7ccf5c9c544c
Create Date: 2026-04-05 19:54:48.029630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '582e583e3461'
down_revision: Union[str, Sequence[str], None] = '7ccf5c9c544c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('role_type_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_roles_role_type'), table_name='roles')
    op.create_index(op.f('ix_roles_role_type_id'), 'roles', ['role_type_id'], unique=False)
    op.create_foreign_key(None, 'roles', 'role_types', ['role_type_id'], ['id'])
    op.drop_column('roles', 'role_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('role_type', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_index(op.f('ix_roles_role_type_id'), table_name='roles')
    op.create_index(op.f('ix_roles_role_type'), 'roles', ['role_type'], unique=False)
    op.drop_column('roles', 'role_type_id')
    # ### end Alembic commands ###
