"""make_manager_appraisal_manager_id_nullable

Revision ID: 67fef5d6b2d4
Revises: 83cba2b54603
Create Date: 2026-06-21 00:22:45.188389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '67fef5d6b2d4'
down_revision: Union[str, Sequence[str], None] = '83cba2b54603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('manager_appraisals', 'manager_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('manager_appraisals', 'manager_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
