"""add soft delete to roles

Revision ID: 6ffa086aab4f
Revises: 6ab56d67ecb5
Create Date: 2026-02-07 17:02:53.888983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ffa086aab4f'
down_revision: Union[str, Sequence[str], None] = '6ab56d67ecb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('roles', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'deleted_at')
    op.drop_column('roles', 'is_deleted')
    # ### end Alembic commands ###
