"""Create organizations table mysql fixed

Revision ID: 72b9b22c2bbe
Revises: 
Create Date: 2026-01-10 15:57:54.114102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.organization


# revision identifiers, used by Alembic.
revision: str = '72b9b22c2bbe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('organization_size', sa.Enum('SIZE_1_10', 'SIZE_11_50', 'SIZE_51_200', 'SIZE_201_500', 'SIZE_500_PLUS', name='organizationsize'), nullable=False),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('gst_number', sa.String(length=50), nullable=True),
    sa.Column('pan_number', sa.String(length=50), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('VERIFICATION_PENDING', 'ACTIVE', 'INACTIVE', 'SUSPENDED', 'TRIAL', name='organizationstatus'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('verification_code', sa.String(length=10), nullable=True),
    sa.Column('verification_code_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legal_name'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_organization_email'), 'organization', ['email'], unique=True)
    op.create_index(op.f('ix_organization_id'), 'organization', ['id'], unique=False)
    op.create_index(op.f('ix_organization_uuid'), 'organization', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_uuid'), table_name='organization')
    op.drop_index(op.f('ix_organization_id'), table_name='organization')
    op.drop_index(op.f('ix_organization_email'), table_name='organization')
    op.drop_table('organization')
    # ### end Alembic commands ###
