"""Add soft delete to ShiftRoster

Revision ID: 77587c5a36c0
Revises: 258807bdb0ca
Create Date: 2026-01-31 15:04:25.685720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77587c5a36c0'
down_revision: Union[str, Sequence[str], None] = '258807bdb0ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_roster', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('shift_roster', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shift_roster', 'deleted_at')
    op.drop_column('shift_roster', 'is_deleted')
    # ### end Alembic commands ###
