"""add_role_types_table

Revision ID: 7ccf5c9c544c
Revises: d9dad313665e
Create Date: 2026-04-05 00:56:41.554628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ccf5c9c544c'
down_revision: Union[str, Sequence[str], None] = 'd9dad313665e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_types_id'), 'role_types', ['id'], unique=False)
    op.create_index(op.f('ix_role_types_name'), 'role_types', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_types_name'), table_name='role_types')
    op.drop_index(op.f('ix_role_types_id'), table_name='role_types')
    op.drop_table('role_types')
    # ### end Alembic commands ###
