"""make appraisal template created_by nullable

Revision ID: 83cba2b54603
Revises: 9f0cb74b0aef
Create Date: 2026-06-17 00:45:15.255745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '83cba2b54603'
down_revision: Union[str, Sequence[str], None] = '9f0cb74b0aef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appraisal_templates', 'created_by',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appraisal_templates', 'created_by',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
