"""add_soft_delete_to_attendance_policy

Revision ID: 85637d645afe
Revises: e046a992aef6
Create Date: 2026-02-05 19:57:23.312516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85637d645afe'
down_revision: Union[str, Sequence[str], None] = 'e046a992aef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_policies', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('attendance_policies', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_attendance_policies_is_deleted'), 'attendance_policies', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_policies_is_deleted'), table_name='attendance_policies')
    op.drop_column('attendance_policies', 'deleted_at')
    op.drop_column('attendance_policies', 'is_deleted')
    # ### end Alembic commands ###
