"""Add regularization soft delete and overtime rejection status

Revision ID: 878d9624c77b
Revises: 77587c5a36c0
Create Date: 2026-02-02 16:35:56.017951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '878d9624c77b'
down_revision: Union[str, Sequence[str], None] = '77587c5a36c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_regularizations', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_attendance_regularizations_is_deleted'), 'attendance_regularizations', ['is_deleted'], unique=False)
    op.add_column('overtime_requests', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('overtime_requests', 'rejection_reason')
    op.drop_index(op.f('ix_attendance_regularizations_is_deleted'), table_name='attendance_regularizations')
    op.drop_column('attendance_regularizations', 'is_deleted')
    # ### end Alembic commands ###
