"""add_soft_delete_to_locations

Revision ID: 87fcd4740066
Revises: d69afaf57f52
Create Date: 2026-01-10 22:19:33.673758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87fcd4740066'
down_revision: Union[str, Sequence[str], None] = 'd69afaf57f52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('locations', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'deleted_at')
    op.drop_column('locations', 'is_deleted')
    # ### end Alembic commands ###
