"""Add Industry model

Revision ID: 96aa4bfa9750
Revises: cd522faf7e95
Create Date: 2026-05-02 23:51:01.716525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import app.models.organization

# revision identifiers, used by Alembic.
revision: str = '96aa4bfa9750'
down_revision: Union[str, Sequence[str], None] = 'cd522faf7e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industries_id'), 'industries', ['id'], unique=False)
    op.create_index(op.f('ix_industries_is_active'), 'industries', ['is_active'], unique=False)
    op.create_index(op.f('ix_industries_name'), 'industries', ['name'], unique=True)
    op.create_index(op.f('ix_industries_uuid'), 'industries', ['uuid'], unique=True)
    op.add_column('organization', sa.Column('industry_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'organization', 'industries', ['industry_id'], ['id'])
    op.alter_column('overtime_requests', 'compensation_type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('paid', 'comp_off', 'both', name='compensationtype'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('overtime_requests', 'compensation_type',
               existing_type=sa.Enum('paid', 'comp_off', 'both', name='compensationtype'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_constraint(None, 'organization', type_='foreignkey')
    op.drop_column('organization', 'industry_id')
    op.drop_index(op.f('ix_industries_uuid'), table_name='industries')
    op.drop_index(op.f('ix_industries_name'), table_name='industries')
    op.drop_index(op.f('ix_industries_is_active'), table_name='industries')
    op.drop_index(op.f('ix_industries_id'), table_name='industries')
    op.drop_table('industries')
    # ### end Alembic commands ###
