"""Add soft delete to ShiftMaster

Revision ID: 9da93a7afdbe
Revises: cdc314f911ac
Create Date: 2026-01-31 13:57:04.633540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da93a7afdbe'
down_revision: Union[str, Sequence[str], None] = 'cdc314f911ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_master', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('shift_master', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shift_master', 'deleted_at')
    op.drop_column('shift_master', 'is_deleted')
    # ### end Alembic commands ###
