"""Add advance_history to AppraisalCycle

Revision ID: 9f0cb74b0aef
Revises: af2d560123ef
Create Date: 2026-06-14 15:38:59.619042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f0cb74b0aef'
down_revision: Union[str, Sequence[str], None] = 'af2d560123ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appraisal_cycles', sa.Column('advance_history', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appraisal_cycles', 'advance_history')
    # ### end Alembic commands ###
