"""Add is_deleted to employee goals

Revision ID: af2d560123ef
Revises: 1d1f21455301
Create Date: 2026-06-13 15:20:46.130905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af2d560123ef'
down_revision: Union[str, Sequence[str], None] = '1d1f21455301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_goals', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_employee_goals_is_deleted'), 'employee_goals', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_goals_is_deleted'), table_name='employee_goals')
    op.drop_column('employee_goals', 'is_deleted')
    # ### end Alembic commands ###
