"""add soft delete fields to timesheets and leave types

Revision ID: b48f1f322303
Revises: 878d9624c77b
Create Date: 2026-02-03 15:43:56.827976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b48f1f322303'
down_revision: Union[str, Sequence[str], None] = '878d9624c77b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_types', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('leave_types', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_leave_types_is_deleted'), 'leave_types', ['is_deleted'], unique=False)
    op.add_column('timesheet_entries', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('timesheets', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timesheets', 'is_deleted')
    op.drop_column('timesheet_entries', 'is_deleted')
    op.drop_index(op.f('ix_leave_types_is_deleted'), table_name='leave_types')
    op.drop_column('leave_types', 'deleted_at')
    op.drop_column('leave_types', 'is_deleted')
    # ### end Alembic commands ###
