"""add_soft_delete_to_holidays

Revision ID: bff7eb76d7c3
Revises: f82670a6e97e
Create Date: 2026-02-03 19:07:37.453124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bff7eb76d7c3'
down_revision: Union[str, Sequence[str], None] = 'f82670a6e97e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holidays', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('holidays', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_holidays_is_deleted'), 'holidays', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_holidays_is_deleted'), table_name='holidays')
    op.drop_column('holidays', 'deleted_at')
    op.drop_column('holidays', 'is_deleted')
    # ### end Alembic commands ###
