"""add_project_task_master_tables

Revision ID: c9fb78cb2d66
Revises: cab28f0dd8f8
Create Date: 2026-05-09 22:02:38.835998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.organization


# revision identifiers, used by Alembic.
revision: str = 'c9fb78cb2d66'
down_revision: Union[str, Sequence[str], None] = 'cab28f0dd8f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('activity_code', sa.String(length=50), nullable=False),
    sa.Column('activity_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_billable_default', sa.Boolean(), nullable=True),
    sa.Column('color_code', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'activity_code', name='uq_activity_org_code')
    )
    op.create_index('idx_activity_org_active', 'activity_types', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_activity_types_activity_code'), 'activity_types', ['activity_code'], unique=False)
    op.create_index(op.f('ix_activity_types_id'), 'activity_types', ['id'], unique=False)
    op.create_index(op.f('ix_activity_types_is_active'), 'activity_types', ['is_active'], unique=False)
    op.create_index(op.f('ix_activity_types_organization_id'), 'activity_types', ['organization_id'], unique=False)
    op.create_index(op.f('ix_activity_types_uuid'), 'activity_types', ['uuid'], unique=True)
    op.create_table('project_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('client_code', sa.String(length=50), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('contact_email', sa.String(length=150), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('billing_currency', sa.String(length=10), nullable=True),
    sa.Column('default_billing_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'client_code', name='uq_client_org_code')
    )
    op.create_index('idx_client_org_active', 'project_clients', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_project_clients_client_code'), 'project_clients', ['client_code'], unique=False)
    op.create_index(op.f('ix_project_clients_id'), 'project_clients', ['id'], unique=False)
    op.create_index(op.f('ix_project_clients_is_active'), 'project_clients', ['is_active'], unique=False)
    op.create_index(op.f('ix_project_clients_organization_id'), 'project_clients', ['organization_id'], unique=False)
    op.create_index(op.f('ix_project_clients_uuid'), 'project_clients', ['uuid'], unique=True)
    op.create_table('timesheet_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('policy_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('period_type', sa.Enum('WEEKLY', 'BI_WEEKLY', 'MONTHLY', name='timesheetperiodtype'), nullable=False),
    sa.Column('submission_deadline_days', sa.Integer(), nullable=True),
    sa.Column('max_hours_per_day', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('min_hours_per_day', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('require_task_selection', sa.Boolean(), nullable=True),
    sa.Column('require_activity_type', sa.Boolean(), nullable=True),
    sa.Column('allow_future_entries', sa.Boolean(), nullable=True),
    sa.Column('allow_backdated_days', sa.Integer(), nullable=True),
    sa.Column('auto_submit', sa.Boolean(), nullable=True),
    sa.Column('applicable_to', sa.Enum('ALL', 'DEPARTMENT', 'EMPLOYEE_TYPE', name='policyapplicableto'), nullable=True),
    sa.Column('department_ids', sa.JSON(), nullable=True),
    sa.Column('employee_type_ids', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ts_policy_org_active', 'timesheet_policies', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_timesheet_policies_id'), 'timesheet_policies', ['id'], unique=False)
    op.create_index(op.f('ix_timesheet_policies_is_active'), 'timesheet_policies', ['is_active'], unique=False)
    op.create_index(op.f('ix_timesheet_policies_organization_id'), 'timesheet_policies', ['organization_id'], unique=False)
    op.create_index(op.f('ix_timesheet_policies_uuid'), 'timesheet_policies', ['uuid'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_type', sa.Enum('BILLABLE', 'NON_BILLABLE', 'INTERNAL', 'RD', name='projecttype'), nullable=False),
    sa.Column('status', sa.Enum('PLANNING', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='projectstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='projectpriority'), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('budget_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('consumed_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('billable_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('budget_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('billing_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('billing_type', sa.Enum('FIXED', 'HOURLY', 'RETAINER', name='billingtype'), nullable=True),
    sa.Column('project_manager_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('color_code', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['project_clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['project_manager_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'project_code', name='uq_project_org_code')
    )
    op.create_index('idx_project_client', 'projects', ['client_id', 'status'], unique=False)
    op.create_index('idx_project_manager', 'projects', ['project_manager_id'], unique=False)
    op.create_index('idx_project_org_status', 'projects', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_projects_client_id'), 'projects', ['client_id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_is_active'), 'projects', ['is_active'], unique=False)
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_index(op.f('ix_projects_project_code'), 'projects', ['project_code'], unique=False)
    op.create_index(op.f('ix_projects_project_manager_id'), 'projects', ['project_manager_id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_uuid'), 'projects', ['uuid'], unique=True)
    op.create_table('project_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('MANAGER', 'DEVELOPER', 'REVIEWER', 'OBSERVER', name='memberrole'), nullable=False),
    sa.Column('billing_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('allocated_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('logged_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('joined_at', sa.Date(), nullable=True),
    sa.Column('left_at', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'employee_id', name='uq_project_member'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_member_employee', 'project_members', ['employee_id', 'is_active'], unique=False)
    op.create_index('idx_member_project_active', 'project_members', ['project_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_project_members_employee_id'), 'project_members', ['employee_id'], unique=False)
    op.create_index(op.f('ix_project_members_id'), 'project_members', ['id'], unique=False)
    op.create_index(op.f('ix_project_members_is_active'), 'project_members', ['is_active'], unique=False)
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_table('project_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('parent_task_id', sa.Integer(), nullable=True),
    sa.Column('task_code', sa.String(length=50), nullable=True),
    sa.Column('task_name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('BACKLOG', 'TODO', 'IN_PROGRESS', 'REVIEW', 'DONE', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='projectpriority'), nullable=True),
    sa.Column('task_type', sa.Enum('FEATURE', 'BUG', 'SUPPORT', 'RESEARCH', 'ADMIN', name='tasktype'), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('estimated_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('logged_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('billable_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_billable', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['parent_task_id'], ['project_tasks.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_assigned', 'project_tasks', ['assigned_to_id', 'status'], unique=False)
    op.create_index('idx_task_org', 'project_tasks', ['organization_id', 'status'], unique=False)
    op.create_index('idx_task_project_status', 'project_tasks', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_project_tasks_assigned_to_id'), 'project_tasks', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_project_tasks_id'), 'project_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_project_tasks_organization_id'), 'project_tasks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_project_tasks_parent_task_id'), 'project_tasks', ['parent_task_id'], unique=False)
    op.create_index(op.f('ix_project_tasks_project_id'), 'project_tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_tasks_status'), 'project_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_project_tasks_task_code'), 'project_tasks', ['task_code'], unique=False)
    op.create_index(op.f('ix_project_tasks_uuid'), 'project_tasks', ['uuid'], unique=True)
    
    # Pre-migration cleanup: NULL out existing loose project_id/task_id to prevent FK integrity errors
    # as the new master tables are currently empty.
    op.execute("UPDATE timesheet_entries SET project_id = NULL, task_id = NULL")
    
    op.add_column('timesheet_entries', sa.Column('activity_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'timesheet_entries', 'project_tasks', ['task_id'], ['id'])
    op.create_foreign_key(None, 'timesheet_entries', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'timesheet_entries', 'activity_types', ['activity_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timesheet_entries', type_='foreignkey')
    op.drop_constraint(None, 'timesheet_entries', type_='foreignkey')
    op.drop_constraint(None, 'timesheet_entries', type_='foreignkey')
    op.drop_column('timesheet_entries', 'activity_type_id')
    op.drop_index(op.f('ix_project_tasks_uuid'), table_name='project_tasks')
    op.drop_index(op.f('ix_project_tasks_task_code'), table_name='project_tasks')
    op.drop_index(op.f('ix_project_tasks_status'), table_name='project_tasks')
    op.drop_index(op.f('ix_project_tasks_project_id'), table_name='project_tasks')
    op.drop_index(op.f('ix_project_tasks_parent_task_id'), table_name='project_tasks')
    op.drop_index(op.f('ix_project_tasks_organization_id'), table_name='project_tasks')
    op.drop_index(op.f('ix_project_tasks_id'), table_name='project_tasks')
    op.drop_index(op.f('ix_project_tasks_assigned_to_id'), table_name='project_tasks')
    op.drop_index('idx_task_project_status', table_name='project_tasks')
    op.drop_index('idx_task_org', table_name='project_tasks')
    op.drop_index('idx_task_assigned', table_name='project_tasks')
    op.drop_table('project_tasks')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_is_active'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_employee_id'), table_name='project_members')
    op.drop_index('idx_member_project_active', table_name='project_members')
    op.drop_index('idx_member_employee', table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_projects_uuid'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_manager_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_code'), table_name='projects')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_active'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_client_id'), table_name='projects')
    op.drop_index('idx_project_org_status', table_name='projects')
    op.drop_index('idx_project_manager', table_name='projects')
    op.drop_index('idx_project_client', table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_timesheet_policies_uuid'), table_name='timesheet_policies')
    op.drop_index(op.f('ix_timesheet_policies_organization_id'), table_name='timesheet_policies')
    op.drop_index(op.f('ix_timesheet_policies_is_active'), table_name='timesheet_policies')
    op.drop_index(op.f('ix_timesheet_policies_id'), table_name='timesheet_policies')
    op.drop_index('idx_ts_policy_org_active', table_name='timesheet_policies')
    op.drop_table('timesheet_policies')
    op.drop_index(op.f('ix_project_clients_uuid'), table_name='project_clients')
    op.drop_index(op.f('ix_project_clients_organization_id'), table_name='project_clients')
    op.drop_index(op.f('ix_project_clients_is_active'), table_name='project_clients')
    op.drop_index(op.f('ix_project_clients_id'), table_name='project_clients')
    op.drop_index(op.f('ix_project_clients_client_code'), table_name='project_clients')
    op.drop_index('idx_client_org_active', table_name='project_clients')
    op.drop_table('project_clients')
    op.drop_index(op.f('ix_activity_types_uuid'), table_name='activity_types')
    op.drop_index(op.f('ix_activity_types_organization_id'), table_name='activity_types')
    op.drop_index(op.f('ix_activity_types_is_active'), table_name='activity_types')
    op.drop_index(op.f('ix_activity_types_id'), table_name='activity_types')
    op.drop_index(op.f('ix_activity_types_activity_code'), table_name='activity_types')
    op.drop_index('idx_activity_org_active', table_name='activity_types')
    op.drop_table('activity_types')
    # ### end Alembic commands ###
