"""add_soft_delete_to_custom_fields

Revision ID: ca07399a2d9c
Revises: cc725dc73f35
Create Date: 2026-01-10 23:27:59.952147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca07399a2d9c'
down_revision: Union[str, Sequence[str], None] = 'cc725dc73f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_field_definitions', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('custom_field_definitions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_field_definitions', 'deleted_at')
    op.drop_column('custom_field_definitions', 'is_deleted')
    # ### end Alembic commands ###
