"""Add Leave templates to quick setup

Revision ID: cab28f0dd8f8
Revises: e792499f4fb0
Create Date: 2026-05-03 00:59:50.409852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cab28f0dd8f8'
down_revision: Union[str, Sequence[str], None] = 'e792499f4fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_leave_policy_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.Column('policy_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('leave_type_codes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_leave_policy_templates_id'), 'industry_leave_policy_templates', ['id'], unique=False)
    op.create_table('industry_leave_type_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.Column('leave_code', sa.String(length=50), nullable=False),
    sa.Column('leave_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('accrual_type', sa.String(length=50), nullable=False),
    sa.Column('accrual_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('annual_quota', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_balance', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('color_code', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_leave_type_templates_id'), 'industry_leave_type_templates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_industry_leave_type_templates_id'), table_name='industry_leave_type_templates')
    op.drop_table('industry_leave_type_templates')
    op.drop_index(op.f('ix_industry_leave_policy_templates_id'), table_name='industry_leave_policy_templates')
    op.drop_table('industry_leave_policy_templates')
    # ### end Alembic commands ###
