"""add_soft_delete_to_cost_centers

Revision ID: cc725dc73f35
Revises: 3927c49ff767
Create Date: 2026-01-10 23:06:24.667046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc725dc73f35'
down_revision: Union[str, Sequence[str], None] = '3927c49ff767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cost_centers', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('cost_centers', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cost_centers', 'deleted_at')
    op.drop_column('cost_centers', 'is_deleted')
    # ### end Alembic commands ###
