"""Fix role code uniqueness with soft delete

Revision ID: cd522faf7e95
Revises: 582e583e3461
Create Date: 2026-04-05 20:09:53.297092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd522faf7e95'
down_revision: Union[str, Sequence[str], None] = '582e583e3461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uniq_role_org_code'), table_name='roles')
    op.create_index('uniq_role_org_code_active', 'roles', ['organization_id', 'role_code', sa.literal_column("(CASE WHEN is_deleted THEN uuid ELSE '0' END)")], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uniq_role_org_code_active', table_name='roles')
    op.create_index(op.f('uniq_role_org_code'), 'roles', ['organization_id', 'role_code'], unique=True)
    # ### end Alembic commands ###
