"""add_soft_delete_to_departments

Revision ID: d69afaf57f52
Revises: ef51a4be036a
Create Date: 2026-01-10 21:44:23.485539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd69afaf57f52'
down_revision: Union[str, Sequence[str], None] = 'ef51a4be036a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('departments', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'deleted_at')
    op.drop_column('departments', 'is_deleted')
    # ### end Alembic commands ###
