"""update_leave_encashment_status_to_enum

Revision ID: e046a992aef6
Revises: bff7eb76d7c3
Create Date: 2026-02-05 19:16:02.615330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e046a992aef6'
down_revision: Union[str, Sequence[str], None] = 'bff7eb76d7c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leave_encashments', 'status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'PAID', name='leaveencashmentstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leave_encashments', 'status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'PAID', name='leaveencashmentstatus'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
