"""Add progress tracking to quick setup

Revision ID: e792499f4fb0
Revises: 52b515439e99
Create Date: 2026-05-03 00:52:23.979067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e792499f4fb0'
down_revision: Union[str, Sequence[str], None] = '52b515439e99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quick_setup_jobs', sa.Column('progress_percentage', sa.Integer(), nullable=True))
    op.add_column('quick_setup_jobs', sa.Column('logs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quick_setup_jobs', 'logs')
    op.drop_column('quick_setup_jobs', 'progress_percentage')
    # ### end Alembic commands ###
