"""add_status_notes_to_organization_goals

Revision ID: eac475b66340
Revises: 3b1877d23329
Create Date: 2026-05-31 17:22:16.551006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eac475b66340'
down_revision: Union[str, Sequence[str], None] = '3b1877d23329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_goals', sa.Column('status_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_goals', 'status_notes')
    # ### end Alembic commands ###
