"""Add Employee models

Revision ID: ef51a4be036a
Revises: a20b4f858d53
Create Date: 2026-01-10 19:46:24.803063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.organization


# revision identifiers, used by Alembic.
revision: str = 'ef51a4be036a'
down_revision: Union[str, Sequence[str], None] = 'a20b4f858d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('department_code', sa.String(length=50), nullable=False),
    sa.Column('department_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_department_id', sa.Integer(), nullable=True),
    sa.Column('head_of_department_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['parent_department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_org_dept_code', 'departments', ['organization_id', 'department_code'], unique=True)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_organization_id'), 'departments', ['organization_id'], unique=False)
    op.create_table('cost_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('cost_center_code', sa.String(length=50), nullable=False),
    sa.Column('cost_center_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_org_cc_code', 'cost_centers', ['organization_id', 'cost_center_code'], unique=True)
    op.create_index(op.f('ix_cost_centers_id'), 'cost_centers', ['id'], unique=False)
    op.create_index(op.f('ix_cost_centers_organization_id'), 'cost_centers', ['organization_id'], unique=False)
    op.create_table('job_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('title_code', sa.String(length=50), nullable=False),
    sa.Column('title_name', sa.String(length=150), nullable=False),
    sa.Column('job_level', sa.String(length=50), nullable=True),
    sa.Column('job_family', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('qualifications', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_org_title_code', 'job_titles', ['organization_id', 'title_code'], unique=True)
    op.create_index(op.f('ix_job_titles_id'), 'job_titles', ['id'], unique=False)
    op.create_index(op.f('ix_job_titles_organization_id'), 'job_titles', ['organization_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('location_code', sa.String(length=50), nullable=False),
    sa.Column('location_name', sa.String(length=150), nullable=False),
    sa.Column('location_type', sa.String(length=50), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('time_zone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_org_loc_code', 'locations', ['organization_id', 'location_code'], unique=True)
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_organization_id'), 'locations', ['organization_id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('preferred_name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='gender'), nullable=True),
    sa.Column('marital_status', sa.Enum('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', 'SEPARATED', name='maritalstatus'), nullable=True),
    sa.Column('blood_group', sa.Enum('A_POSITIVE', 'A_NEGATIVE', 'B_POSITIVE', 'B_NEGATIVE', 'O_POSITIVE', 'O_NEGATIVE', 'AB_POSITIVE', 'AB_NEGATIVE', name='bloodgroup'), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('personal_email', sa.String(length=255), nullable=True),
    sa.Column('work_email', sa.String(length=255), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=True),
    sa.Column('alternate_mobile_number', sa.String(length=20), nullable=True),
    sa.Column('work_phone', sa.String(length=20), nullable=True),
    sa.Column('work_phone_extension', sa.String(length=10), nullable=True),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'TEMPORARY', 'INTERN', 'CONSULTANT', name='employmenttype'), nullable=False),
    sa.Column('employment_status', sa.Enum('ACTIVE', 'INACTIVE', 'ON_LEAVE', 'PROBATION', 'NOTICE_PERIOD', 'TERMINATED', 'RESIGNED', 'RETIRED', name='employmentstatus'), nullable=False),
    sa.Column('date_of_joining', sa.Date(), nullable=False),
    sa.Column('date_of_confirmation', sa.Date(), nullable=True),
    sa.Column('probation_end_date', sa.Date(), nullable=True),
    sa.Column('notice_period_days', sa.Integer(), nullable=True),
    sa.Column('date_of_leaving', sa.Date(), nullable=True),
    sa.Column('job_title_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('cost_center_id', sa.Integer(), nullable=True),
    sa.Column('reporting_manager_id', sa.Integer(), nullable=True),
    sa.Column('functional_manager_id', sa.Integer(), nullable=True),
    sa.Column('photograph_url', sa.String(length=500), nullable=True),
    sa.Column('signature_url', sa.String(length=500), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['functional_manager_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['job_title_id'], ['job_titles.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['reporting_manager_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_org_active', 'employees', ['organization_id', 'is_active'], unique=False)
    op.create_index('idx_org_emp_code', 'employees', ['organization_id', 'employee_code'], unique=True)
    op.create_index('idx_org_emp_status', 'employees', ['organization_id', 'employment_status'], unique=False)
    op.create_index(op.f('ix_employees_date_of_joining'), 'employees', ['date_of_joining'], unique=False)
    op.create_index(op.f('ix_employees_department_id'), 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=False)
    op.create_index(op.f('ix_employees_employment_status'), 'employees', ['employment_status'], unique=False)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_is_active'), 'employees', ['is_active'], unique=False)
    op.create_index(op.f('ix_employees_location_id'), 'employees', ['location_id'], unique=False)
    op.create_index(op.f('ix_employees_organization_id'), 'employees', ['organization_id'], unique=False)
    op.create_index(op.f('ix_employees_personal_email'), 'employees', ['personal_email'], unique=False)
    op.create_index(op.f('ix_employees_reporting_manager_id'), 'employees', ['reporting_manager_id'], unique=False)
    op.create_index(op.f('ix_employees_uuid'), 'employees', ['uuid'], unique=True)
    op.create_index(op.f('ix_employees_work_email'), 'employees', ['work_email'], unique=True)
    op.create_table('custom_field_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_label', sa.String(length=150), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('field_options', sa.JSON(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_searchable', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_org_custom_field', 'custom_field_definitions', ['organization_id', 'field_name'], unique=True)
    op.create_index(op.f('ix_custom_field_definitions_id'), 'custom_field_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_custom_field_definitions_organization_id'), 'custom_field_definitions', ['organization_id'], unique=False)
    op.create_table('employee_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('address_type', sa.String(length=20), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('landmark', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_emp_addr_type', 'employee_addresses', ['employee_id', 'address_type'], unique=False)
    op.create_index(op.f('ix_employee_addresses_employee_id'), 'employee_addresses', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_addresses_id'), 'employee_addresses', ['id'], unique=False)
    op.create_table('employee_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.Enum('DOCUMENT_EXPIRY', 'PROBATION_COMPLETION', 'CONTRACT_RENEWAL', 'BIRTHDAY', 'WORK_ANNIVERSARY', 'CERTIFICATION_EXPIRY', name='alerttype'), nullable=False),
    sa.Column('alert_date', sa.Date(), nullable=False),
    sa.Column('alert_title', sa.String(length=255), nullable=False),
    sa.Column('alert_message', sa.Text(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_alert_date_type', 'employee_alerts', ['alert_date', 'alert_type'], unique=False)
    op.create_index('idx_alert_pending', 'employee_alerts', ['is_sent', 'alert_date'], unique=False)
    op.create_index(op.f('ix_employee_alerts_alert_date'), 'employee_alerts', ['alert_date'], unique=False)
    op.create_index(op.f('ix_employee_alerts_alert_type'), 'employee_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_employee_alerts_employee_id'), 'employee_alerts', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_alerts_id'), 'employee_alerts', ['id'], unique=False)
    op.create_table('employee_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_audit_created', 'employee_audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_emp_table', 'employee_audit_logs', ['employee_id', 'table_name'], unique=False)
    op.create_index(op.f('ix_employee_audit_logs_created_at'), 'employee_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_employee_audit_logs_employee_id'), 'employee_audit_logs', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_audit_logs_id'), 'employee_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_employee_audit_logs_table_name'), 'employee_audit_logs', ['table_name'], unique=False)
    op.create_table('employee_certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('certification_name', sa.String(length=255), nullable=False),
    sa.Column('issuing_organization', sa.String(length=255), nullable=False),
    sa.Column('certification_id', sa.String(length=100), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('credential_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_certifications_employee_id'), 'employee_certifications', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_certifications_expiry_date'), 'employee_certifications', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_employee_certifications_id'), 'employee_certifications', ['id'], unique=False)
    op.create_table('employee_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('CONTRACT', 'OFFER_LETTER', 'APPOINTMENT_LETTER', 'RELIEVING_LETTER', 'EXPERIENCE_CERTIFICATE', 'CERTIFICATION', 'LICENSE', 'EDUCATIONAL_DOCUMENT', 'IDENTITY_PROOF', 'ADDRESS_PROOF', 'PERFORMANCE_REVIEW', 'WARNING_LETTER', 'INCREMENT_LETTER', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_size_kb', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('issuing_authority', sa.String(length=200), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('is_confidential', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_doc_expiry', 'employee_documents', ['expiry_date'], unique=False)
    op.create_index('idx_emp_doc_type', 'employee_documents', ['employee_id', 'document_type'], unique=False)
    op.create_index(op.f('ix_employee_documents_employee_id'), 'employee_documents', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_documents_expiry_date'), 'employee_documents', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_employee_documents_id'), 'employee_documents', ['id'], unique=False)
    op.create_table('employee_education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('degree_name', sa.String(length=150), nullable=False),
    sa.Column('field_of_study', sa.String(length=150), nullable=True),
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('university_name', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('grade_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cgpa', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('is_highest_qualification', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_education_employee_id'), 'employee_education', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_education_id'), 'employee_education', ['id'], unique=False)
    op.create_table('employee_emergency_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(length=150), nullable=False),
    sa.Column('relationship', sa.Enum('FATHER', 'MOTHER', 'SPOUSE', 'SIBLING', 'CHILD', 'FRIEND', 'GUARDIAN', 'OTHER', name='contactrelationship'), nullable=False),
    sa.Column('primary_phone', sa.String(length=20), nullable=False),
    sa.Column('alternate_phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('priority_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_emergency_contacts_employee_id'), 'employee_emergency_contacts', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_emergency_contacts_id'), 'employee_emergency_contacts', ['id'], unique=False)
    op.create_table('employee_personal_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('pan_number', sa.String(length=50), nullable=True),
    sa.Column('aadhar_number', sa.String(length=50), nullable=True),
    sa.Column('passport_number', sa.String(length=50), nullable=True),
    sa.Column('passport_expiry_date', sa.Date(), nullable=True),
    sa.Column('passport_issue_country', sa.String(length=100), nullable=True),
    sa.Column('driving_license_number', sa.String(length=50), nullable=True),
    sa.Column('driving_license_expiry_date', sa.Date(), nullable=True),
    sa.Column('social_security_number', sa.String(length=50), nullable=True),
    sa.Column('national_id_number', sa.String(length=50), nullable=True),
    sa.Column('place_of_birth', sa.String(length=100), nullable=True),
    sa.Column('religion', sa.String(length=50), nullable=True),
    sa.Column('caste_category', sa.String(length=50), nullable=True),
    sa.Column('differently_abled', sa.Boolean(), nullable=True),
    sa.Column('disability_details', sa.Text(), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('identification_marks', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('twitter_handle', sa.String(length=100), nullable=True),
    sa.Column('facebook_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_personal_info_employee_id'), 'employee_personal_info', ['employee_id'], unique=True)
    op.create_index(op.f('ix_employee_personal_info_id'), 'employee_personal_info', ['id'], unique=False)
    op.create_table('employee_work_experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=150), nullable=False),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reason_for_leaving', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_work_experience_employee_id'), 'employee_work_experience', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_work_experience_id'), 'employee_work_experience', ['id'], unique=False)
    op.create_table('employee_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.Enum('HIRE', 'PROMOTION', 'TRANSFER', 'DEMOTION', 'SALARY_REVISION', 'DEPARTMENT_CHANGE', 'LOCATION_CHANGE', 'DESIGNATION_CHANGE', 'REPORTING_CHANGE', 'TERMINATION', 'RESIGNATION', name='changetype'), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('previous_job_title_id', sa.Integer(), nullable=True),
    sa.Column('previous_department_id', sa.Integer(), nullable=True),
    sa.Column('previous_location_id', sa.Integer(), nullable=True),
    sa.Column('previous_reporting_manager_id', sa.Integer(), nullable=True),
    sa.Column('previous_employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'TEMPORARY', 'INTERN', 'CONSULTANT', name='employmenttype'), nullable=True),
    sa.Column('previous_employment_status', sa.Enum('ACTIVE', 'INACTIVE', 'ON_LEAVE', 'PROBATION', 'NOTICE_PERIOD', 'TERMINATED', 'RESIGNED', 'RETIRED', name='employmentstatus'), nullable=True),
    sa.Column('previous_salary', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('new_job_title_id', sa.Integer(), nullable=True),
    sa.Column('new_department_id', sa.Integer(), nullable=True),
    sa.Column('new_location_id', sa.Integer(), nullable=True),
    sa.Column('new_reporting_manager_id', sa.Integer(), nullable=True),
    sa.Column('new_employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'TEMPORARY', 'INTERN', 'CONSULTANT', name='employmenttype'), nullable=True),
    sa.Column('new_employment_status', sa.Enum('ACTIVE', 'INACTIVE', 'ON_LEAVE', 'PROBATION', 'NOTICE_PERIOD', 'TERMINATED', 'RESIGNED', 'RETIRED', name='employmentstatus'), nullable=True),
    sa.Column('new_salary', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['new_department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['new_job_title_id'], ['job_titles.id'], ),
    sa.ForeignKeyConstraint(['new_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['new_reporting_manager_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['previous_department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['previous_job_title_id'], ['job_titles.id'], ),
    sa.ForeignKeyConstraint(['previous_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['previous_reporting_manager_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_employee_history_change_type'), 'employee_history', ['change_type'], unique=False)
    op.create_index(op.f('ix_employee_history_effective_date'), 'employee_history', ['effective_date'], unique=False)
    op.create_index(op.f('ix_employee_history_employee_id'), 'employee_history', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_history_id'), 'employee_history', ['id'], unique=False)
    op.create_foreign_key('fk_dept_head', 'departments', 'employees', ['head_of_department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_history_id'), table_name='employee_history')
    op.drop_index(op.f('ix_employee_history_employee_id'), table_name='employee_history')
    op.drop_index(op.f('ix_employee_history_effective_date'), table_name='employee_history')
    op.drop_index(op.f('ix_employee_history_change_type'), table_name='employee_history')
    op.drop_table('employee_history')
    op.drop_index(op.f('ix_locations_organization_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_index('idx_org_loc_code', table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_job_titles_organization_id'), table_name='job_titles')
    op.drop_index(op.f('ix_job_titles_id'), table_name='job_titles')
    op.drop_index('idx_org_title_code', table_name='job_titles')
    op.drop_table('job_titles')
    op.drop_index(op.f('ix_employee_work_experience_id'), table_name='employee_work_experience')
    op.drop_index(op.f('ix_employee_work_experience_employee_id'), table_name='employee_work_experience')
    op.drop_table('employee_work_experience')
    op.drop_index(op.f('ix_employee_personal_info_id'), table_name='employee_personal_info')
    op.drop_index(op.f('ix_employee_personal_info_employee_id'), table_name='employee_personal_info')
    op.drop_table('employee_personal_info')
    op.drop_index(op.f('ix_employee_emergency_contacts_id'), table_name='employee_emergency_contacts')
    op.drop_index(op.f('ix_employee_emergency_contacts_employee_id'), table_name='employee_emergency_contacts')
    op.drop_table('employee_emergency_contacts')
    op.drop_index(op.f('ix_employee_education_id'), table_name='employee_education')
    op.drop_index(op.f('ix_employee_education_employee_id'), table_name='employee_education')
    op.drop_table('employee_education')
    op.drop_index(op.f('ix_employee_documents_id'), table_name='employee_documents')
    op.drop_index(op.f('ix_employee_documents_expiry_date'), table_name='employee_documents')
    op.drop_index(op.f('ix_employee_documents_employee_id'), table_name='employee_documents')
    op.drop_index('idx_emp_doc_type', table_name='employee_documents')
    op.drop_index('idx_doc_expiry', table_name='employee_documents')
    op.drop_table('employee_documents')
    op.drop_index(op.f('ix_employee_certifications_id'), table_name='employee_certifications')
    op.drop_index(op.f('ix_employee_certifications_expiry_date'), table_name='employee_certifications')
    op.drop_index(op.f('ix_employee_certifications_employee_id'), table_name='employee_certifications')
    op.drop_table('employee_certifications')
    op.drop_index(op.f('ix_employee_audit_logs_table_name'), table_name='employee_audit_logs')
    op.drop_index(op.f('ix_employee_audit_logs_id'), table_name='employee_audit_logs')
    op.drop_index(op.f('ix_employee_audit_logs_employee_id'), table_name='employee_audit_logs')
    op.drop_index(op.f('ix_employee_audit_logs_created_at'), table_name='employee_audit_logs')
    op.drop_index('idx_audit_emp_table', table_name='employee_audit_logs')
    op.drop_index('idx_audit_created', table_name='employee_audit_logs')
    op.drop_table('employee_audit_logs')
    op.drop_index(op.f('ix_employee_alerts_id'), table_name='employee_alerts')
    op.drop_index(op.f('ix_employee_alerts_employee_id'), table_name='employee_alerts')
    op.drop_index(op.f('ix_employee_alerts_alert_type'), table_name='employee_alerts')
    op.drop_index(op.f('ix_employee_alerts_alert_date'), table_name='employee_alerts')
    op.drop_index('idx_alert_pending', table_name='employee_alerts')
    op.drop_index('idx_alert_date_type', table_name='employee_alerts')
    op.drop_table('employee_alerts')
    op.drop_index(op.f('ix_employee_addresses_id'), table_name='employee_addresses')
    op.drop_index(op.f('ix_employee_addresses_employee_id'), table_name='employee_addresses')
    op.drop_index('idx_emp_addr_type', table_name='employee_addresses')
    op.drop_table('employee_addresses')
    op.drop_index(op.f('ix_custom_field_definitions_organization_id'), table_name='custom_field_definitions')
    op.drop_index(op.f('ix_custom_field_definitions_id'), table_name='custom_field_definitions')
    op.drop_index('idx_org_custom_field', table_name='custom_field_definitions')
    op.drop_table('custom_field_definitions')
    op.drop_index(op.f('ix_cost_centers_organization_id'), table_name='cost_centers')
    op.drop_index(op.f('ix_cost_centers_id'), table_name='cost_centers')
    op.drop_index('idx_org_cc_code', table_name='cost_centers')
    op.drop_table('cost_centers')
    op.drop_index(op.f('ix_employees_work_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_uuid'), table_name='employees')
    op.drop_index(op.f('ix_employees_reporting_manager_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_personal_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_organization_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_location_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_is_active'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employment_status'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_date_of_joining'), table_name='employees')
    op.drop_index('idx_org_emp_status', table_name='employees')
    op.drop_index('idx_org_emp_code', table_name='employees')
    op.drop_index('idx_org_active', table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_departments_organization_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index('idx_org_dept_code', table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
