"""Add payroll models

Revision ID: f33bd7cae80a
Revises: c9fb78cb2d66
Create Date: 2026-05-12 00:28:48.287919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.organization


# revision identifiers, used by Alembic.
revision: str = 'f33bd7cae80a'
down_revision: Union[str, Sequence[str], None] = 'c9fb78cb2d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('loan_type', sa.String(length=50), nullable=False),
    sa.Column('loan_number', sa.String(length=50), nullable=False),
    sa.Column('loan_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_payable', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('repayment_start_date', sa.Date(), nullable=False),
    sa.Column('number_of_installments', sa.Integer(), nullable=False),
    sa.Column('monthly_installment', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('installments_paid', sa.Integer(), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('outstanding_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'ACTIVE', 'COMPLETED', 'REJECTED', 'WRITTEN_OFF', name='loanstatus'), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approval_comments', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('disbursement_date', sa.Date(), nullable=True),
    sa.Column('disbursement_mode', sa.String(length=20), nullable=True),
    sa.Column('disbursement_reference', sa.String(length=100), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('guarantor_employee_id', sa.Integer(), nullable=True),
    sa.Column('attachment_urls', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['guarantor_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_loan_emp_status', 'employee_loans', ['employee_id', 'status'], unique=False)
    op.create_index(op.f('ix_employee_loans_employee_id'), 'employee_loans', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_loans_id'), 'employee_loans', ['id'], unique=False)
    op.create_index(op.f('ix_employee_loans_loan_number'), 'employee_loans', ['loan_number'], unique=True)
    op.create_index(op.f('ix_employee_loans_organization_id'), 'employee_loans', ['organization_id'], unique=False)
    op.create_index(op.f('ix_employee_loans_status'), 'employee_loans', ['status'], unique=False)
    op.create_index(op.f('ix_employee_loans_uuid'), 'employee_loans', ['uuid'], unique=True)
    op.create_table('final_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('settlement_number', sa.String(length=50), nullable=False),
    sa.Column('last_working_date', sa.Date(), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=False),
    sa.Column('separation_type', sa.String(length=50), nullable=False),
    sa.Column('total_years', sa.Integer(), nullable=False),
    sa.Column('total_months', sa.Integer(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('last_month_days_worked', sa.Integer(), nullable=False),
    sa.Column('last_month_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('leave_balance_days', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('leave_encashment_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notice_period_days', sa.Integer(), nullable=False),
    sa.Column('notice_period_served', sa.Integer(), nullable=False),
    sa.Column('notice_period_shortage', sa.Integer(), nullable=True),
    sa.Column('notice_pay_recovery', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_gratuity_applicable', sa.Boolean(), nullable=True),
    sa.Column('gratuity_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bonus_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pending_reimbursements', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('asset_recovery', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('loan_recovery', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('other_recoveries', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_recoveries', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_earnings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_settlement_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_deducted', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('payment_mode', sa.String(length=20), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('settlement_letter_url', sa.String(length=500), nullable=True),
    sa.Column('calculation_sheet_url', sa.String(length=500), nullable=True),
    sa.Column('earning_breakdown', sa.JSON(), nullable=True),
    sa.Column('deduction_breakdown', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_final_settlements_employee_id'), 'final_settlements', ['employee_id'], unique=True)
    op.create_index(op.f('ix_final_settlements_id'), 'final_settlements', ['id'], unique=False)
    op.create_index(op.f('ix_final_settlements_organization_id'), 'final_settlements', ['organization_id'], unique=False)
    op.create_index(op.f('ix_final_settlements_settlement_number'), 'final_settlements', ['settlement_number'], unique=True)
    op.create_index(op.f('ix_final_settlements_status'), 'final_settlements', ['status'], unique=False)
    op.create_index(op.f('ix_final_settlements_uuid'), 'final_settlements', ['uuid'], unique=True)
    op.create_table('payroll_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('changed_fields', sa.JSON(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_payroll_audit_action', 'payroll_audit_logs', ['action_type', 'performed_at'], unique=False)
    op.create_index('idx_payroll_audit_entity', 'payroll_audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_payroll_audit_logs_action_type'), 'payroll_audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_payroll_audit_logs_employee_id'), 'payroll_audit_logs', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_audit_logs_entity_id'), 'payroll_audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_payroll_audit_logs_id'), 'payroll_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_audit_logs_organization_id'), 'payroll_audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_payroll_audit_logs_performed_at'), 'payroll_audit_logs', ['performed_at'], unique=False)
    op.create_index(op.f('ix_payroll_audit_logs_performed_by'), 'payroll_audit_logs', ['performed_by'], unique=False)
    op.create_table('payroll_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('period_name', sa.String(length=100), nullable=False),
    sa.Column('period_code', sa.String(length=50), nullable=False),
    sa.Column('period_start_date', sa.Date(), nullable=False),
    sa.Column('period_end_date', sa.Date(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('pay_frequency', sa.Enum('MONTHLY', 'BI_WEEKLY', 'WEEKLY', 'SEMI_MONTHLY', 'QUARTERLY', name='payfrequency'), nullable=False),
    sa.Column('total_working_days', sa.Integer(), nullable=False),
    sa.Column('financial_year', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_PROGRESS', 'PENDING_APPROVAL', 'APPROVED', 'PROCESSED', 'PUBLISHED', 'PAID', 'REVERSED', 'ON_HOLD', name='payrollstatus'), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(), nullable=True),
    sa.Column('processed_by', sa.Integer(), nullable=True),
    sa.Column('submitted_for_approval_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approval_comments', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('published_by', sa.Integer(), nullable=True),
    sa.Column('payment_processed_at', sa.DateTime(), nullable=True),
    sa.Column('payment_processed_by', sa.Integer(), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('total_employees', sa.Integer(), nullable=True),
    sa.Column('total_gross_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_deductions', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_net_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_employer_contributions', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_on_hold', sa.Boolean(), nullable=True),
    sa.Column('hold_reason', sa.Text(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('locked_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['locked_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['payment_processed_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['published_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payroll_period_dates', 'payroll_periods', ['period_start_date', 'period_end_date'], unique=False)
    op.create_index('idx_payroll_period_fy_status', 'payroll_periods', ['financial_year', 'status'], unique=False)
    op.create_index('idx_payroll_period_org_code', 'payroll_periods', ['organization_id', 'period_code'], unique=True)
    op.create_index('idx_payroll_period_status', 'payroll_periods', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_payroll_periods_id'), 'payroll_periods', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_periods_is_locked'), 'payroll_periods', ['is_locked'], unique=False)
    op.create_index(op.f('ix_payroll_periods_organization_id'), 'payroll_periods', ['organization_id'], unique=False)
    op.create_index(op.f('ix_payroll_periods_period_end_date'), 'payroll_periods', ['period_end_date'], unique=False)
    op.create_index(op.f('ix_payroll_periods_period_start_date'), 'payroll_periods', ['period_start_date'], unique=False)
    op.create_index(op.f('ix_payroll_periods_status'), 'payroll_periods', ['status'], unique=False)
    op.create_index(op.f('ix_payroll_periods_uuid'), 'payroll_periods', ['uuid'], unique=True)
    op.create_table('reimbursement_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('category_code', sa.String(length=50), nullable=False),
    sa.Column('category_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_claim_per_month', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_claim_per_year', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_claim_per_transaction', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('approval_limit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('requires_receipt', sa.Boolean(), nullable=True),
    sa.Column('receipt_mandatory_above', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('is_taxable', sa.Boolean(), nullable=True),
    sa.Column('applicable_to_employee_types', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('idx_reimb_cat_org_code', 'reimbursement_categories', ['organization_id', 'category_code'], unique=True)
    op.create_index(op.f('ix_reimbursement_categories_id'), 'reimbursement_categories', ['id'], unique=False)
    op.create_index(op.f('ix_reimbursement_categories_organization_id'), 'reimbursement_categories', ['organization_id'], unique=False)
    op.create_table('salary_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('component_code', sa.String(length=50), nullable=False),
    sa.Column('component_name', sa.String(length=150), nullable=False),
    sa.Column('component_type', sa.Enum('EARNING', 'DEDUCTION', 'EMPLOYER_CONTRIBUTION', name='componenttype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('calculation_type', sa.Enum('FIXED', 'PERCENTAGE', 'FORMULA', 'ATTENDANCE_BASED', 'PERFORMANCE_BASED', name='calculationtype'), nullable=False),
    sa.Column('calculation_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('calculation_formula', sa.Text(), nullable=True),
    sa.Column('based_on_component_ids', sa.JSON(), nullable=True),
    sa.Column('is_taxable', sa.Boolean(), nullable=True),
    sa.Column('is_part_of_gross', sa.Boolean(), nullable=True),
    sa.Column('is_part_of_ctc', sa.Boolean(), nullable=True),
    sa.Column('exemption_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('has_employer_contribution', sa.Boolean(), nullable=True),
    sa.Column('employer_contribution_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('has_employee_contribution', sa.Boolean(), nullable=True),
    sa.Column('employee_contribution_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('show_on_payslip', sa.Boolean(), nullable=True),
    sa.Column('applicable_to_employee_types', sa.JSON(), nullable=True),
    sa.Column('min_salary_for_applicability', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pay_frequency_override', sa.Enum('MONTHLY', 'BI_WEEKLY', 'WEEKLY', 'SEMI_MONTHLY', 'QUARTERLY', name='payfrequency'), nullable=True),
    sa.Column('is_prorated', sa.Boolean(), nullable=True),
    sa.Column('proration_based_on', sa.String(length=20), nullable=True),
    sa.Column('statutory_component_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sal_comp_org_code', 'salary_components', ['organization_id', 'component_code'], unique=True)
    op.create_index(op.f('ix_salary_components_component_code'), 'salary_components', ['component_code'], unique=False)
    op.create_index(op.f('ix_salary_components_id'), 'salary_components', ['id'], unique=False)
    op.create_index(op.f('ix_salary_components_is_active'), 'salary_components', ['is_active'], unique=False)
    op.create_index(op.f('ix_salary_components_organization_id'), 'salary_components', ['organization_id'], unique=False)
    op.create_index(op.f('ix_salary_components_uuid'), 'salary_components', ['uuid'], unique=True)
    op.create_table('salary_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('template_code', sa.String(length=50), nullable=False),
    sa.Column('template_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('applicable_to', sa.String(length=50), nullable=True),
    sa.Column('grade_ids', sa.JSON(), nullable=True),
    sa.Column('department_ids', sa.JSON(), nullable=True),
    sa.Column('location_ids', sa.JSON(), nullable=True),
    sa.Column('employment_types', sa.JSON(), nullable=True),
    sa.Column('annual_ctc_min', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('annual_ctc_max', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pay_frequency', sa.Enum('MONTHLY', 'BI_WEEKLY', 'WEEKLY', 'SEMI_MONTHLY', 'QUARTERLY', name='payfrequency'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sal_template_org_code', 'salary_templates', ['organization_id', 'template_code'], unique=True)
    op.create_index(op.f('ix_salary_templates_id'), 'salary_templates', ['id'], unique=False)
    op.create_index(op.f('ix_salary_templates_organization_id'), 'salary_templates', ['organization_id'], unique=False)
    op.create_index(op.f('ix_salary_templates_uuid'), 'salary_templates', ['uuid'], unique=True)
    op.create_table('statutory_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('form_type', sa.String(length=50), nullable=False),
    sa.Column('form_name', sa.String(length=150), nullable=False),
    sa.Column('form_number', sa.String(length=50), nullable=False),
    sa.Column('financial_year', sa.String(length=20), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=True),
    sa.Column('period_start_date', sa.Date(), nullable=True),
    sa.Column('period_end_date', sa.Date(), nullable=True),
    sa.Column('filing_deadline', sa.Date(), nullable=True),
    sa.Column('filing_status', sa.String(length=20), nullable=False),
    sa.Column('filed_at', sa.DateTime(), nullable=True),
    sa.Column('filed_by', sa.Integer(), nullable=True),
    sa.Column('filing_reference', sa.String(length=100), nullable=True),
    sa.Column('acknowledgment_number', sa.String(length=100), nullable=True),
    sa.Column('form_url', sa.String(length=500), nullable=True),
    sa.Column('acknowledgment_url', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['filed_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_number')
    )
    op.create_index(op.f('ix_statutory_forms_id'), 'statutory_forms', ['id'], unique=False)
    op.create_index(op.f('ix_statutory_forms_organization_id'), 'statutory_forms', ['organization_id'], unique=False)
    op.create_index(op.f('ix_statutory_forms_uuid'), 'statutory_forms', ['uuid'], unique=True)
    op.create_table('tax_calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('financial_year', sa.String(length=20), nullable=False),
    sa.Column('calculation_type', sa.String(length=20), nullable=False),
    sa.Column('tax_regime', sa.Enum('OLD', 'NEW', 'DEFAULT', name='taxregime'), nullable=False),
    sa.Column('gross_annual_income', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('standard_deduction', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hra_exemption', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lta_exemption', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('professional_tax', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('total_80c_deductions', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_80d_deductions', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_other_deductions', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_deductions', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('taxable_income', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_on_income', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('surcharge', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cess', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rebate_under_87a', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('net_tax_payable', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_tds', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tds_deducted_ytd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('remaining_tds', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_slab_breakdown', sa.JSON(), nullable=True),
    sa.Column('deduction_breakdown', sa.JSON(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.Column('calculated_by', sa.Integer(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['calculated_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tax_calc_emp_fy', 'tax_calculations', ['employee_id', 'financial_year'], unique=False)
    op.create_index(op.f('ix_tax_calculations_employee_id'), 'tax_calculations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_tax_calculations_id'), 'tax_calculations', ['id'], unique=False)
    op.create_index(op.f('ix_tax_calculations_organization_id'), 'tax_calculations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tax_calculations_uuid'), 'tax_calculations', ['uuid'], unique=True)
    op.create_table('tax_declarations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('financial_year', sa.String(length=20), nullable=False),
    sa.Column('tax_regime', sa.Enum('OLD', 'NEW', 'DEFAULT', name='taxregime'), nullable=False),
    sa.Column('declaration_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewer_comments', sa.Text(), nullable=True),
    sa.Column('proofs_submitted', sa.Boolean(), nullable=True),
    sa.Column('proof_submission_date', sa.Date(), nullable=True),
    sa.Column('total_declared_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_approved_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tax_decl_emp_fy', 'tax_declarations', ['employee_id', 'financial_year'], unique=False)
    op.create_index('idx_tax_decl_emp_status', 'tax_declarations', ['employee_id', 'status', 'financial_year'], unique=False)
    op.create_index(op.f('ix_tax_declarations_employee_id'), 'tax_declarations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_tax_declarations_id'), 'tax_declarations', ['id'], unique=False)
    op.create_index(op.f('ix_tax_declarations_organization_id'), 'tax_declarations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tax_declarations_status'), 'tax_declarations', ['status'], unique=False)
    op.create_index(op.f('ix_tax_declarations_uuid'), 'tax_declarations', ['uuid'], unique=True)
    op.create_table('bank_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('payroll_period_id', sa.Integer(), nullable=False),
    sa.Column('file_number', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('bank_name', sa.String(length=150), nullable=True),
    sa.Column('file_format', sa.String(length=50), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('generated_by', sa.Integer(), nullable=False),
    sa.Column('is_uploaded', sa.Boolean(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('upload_reference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('bank_confirmation_received', sa.Boolean(), nullable=True),
    sa.Column('bank_confirmation_date', sa.Date(), nullable=True),
    sa.Column('bank_utr_numbers', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_number')
    )
    op.create_index(op.f('ix_bank_files_id'), 'bank_files', ['id'], unique=False)
    op.create_index(op.f('ix_bank_files_organization_id'), 'bank_files', ['organization_id'], unique=False)
    op.create_index(op.f('ix_bank_files_payroll_period_id'), 'bank_files', ['payroll_period_id'], unique=False)
    op.create_index(op.f('ix_bank_files_uuid'), 'bank_files', ['uuid'], unique=True)
    op.create_table('employee_salaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('annual_ctc', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('monthly_ctc', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_gross', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_net', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pay_frequency', sa.Enum('MONTHLY', 'BI_WEEKLY', 'WEEKLY', 'SEMI_MONTHLY', 'QUARTERLY', name='payfrequency'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('payment_mode', sa.String(length=20), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('revision_number', sa.Integer(), nullable=True),
    sa.Column('previous_salary_id', sa.Integer(), nullable=True),
    sa.Column('revision_reason', sa.String(length=100), nullable=True),
    sa.Column('revision_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_on_hold', sa.Boolean(), nullable=True),
    sa.Column('hold_reason', sa.Text(), nullable=True),
    sa.Column('hold_from_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['bank_account_id'], ['employee_bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['previous_salary_id'], ['employee_salaries.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['salary_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_emp_sal_effective', 'employee_salaries', ['employee_id', 'effective_from', 'effective_to'], unique=False)
    op.create_index('idx_emp_sal_emp_active', 'employee_salaries', ['employee_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_employee_salaries_effective_from'), 'employee_salaries', ['effective_from'], unique=False)
    op.create_index(op.f('ix_employee_salaries_effective_to'), 'employee_salaries', ['effective_to'], unique=False)
    op.create_index(op.f('ix_employee_salaries_employee_id'), 'employee_salaries', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_salaries_id'), 'employee_salaries', ['id'], unique=False)
    op.create_index(op.f('ix_employee_salaries_is_active'), 'employee_salaries', ['is_active'], unique=False)
    op.create_index(op.f('ix_employee_salaries_is_on_hold'), 'employee_salaries', ['is_on_hold'], unique=False)
    op.create_index(op.f('ix_employee_salaries_organization_id'), 'employee_salaries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_employee_salaries_uuid'), 'employee_salaries', ['uuid'], unique=True)
    op.create_table('payroll_journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('payroll_period_id', sa.Integer(), nullable=False),
    sa.Column('entry_number', sa.String(length=50), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('accounting_period', sa.String(length=20), nullable=False),
    sa.Column('financial_year', sa.String(length=20), nullable=False),
    sa.Column('entry_type', sa.String(length=50), nullable=False),
    sa.Column('total_debit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_credit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_exported', sa.Boolean(), nullable=True),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.Column('export_reference', sa.String(length=100), nullable=True),
    sa.Column('erp_journal_id', sa.String(length=100), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(), nullable=True),
    sa.Column('reversal_entry_id', sa.Integer(), nullable=True),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], ),
    sa.ForeignKeyConstraint(['reversal_entry_id'], ['payroll_journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_number')
    )
    op.create_index(op.f('ix_payroll_journal_entries_id'), 'payroll_journal_entries', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_journal_entries_organization_id'), 'payroll_journal_entries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_payroll_journal_entries_payroll_period_id'), 'payroll_journal_entries', ['payroll_period_id'], unique=False)
    op.create_index(op.f('ix_payroll_journal_entries_uuid'), 'payroll_journal_entries', ['uuid'], unique=True)
    op.create_table('payroll_reconciliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('payroll_period_id', sa.Integer(), nullable=False),
    sa.Column('reconciliation_number', sa.String(length=50), nullable=False),
    sa.Column('reconciliation_date', sa.Date(), nullable=False),
    sa.Column('previous_period_id', sa.Integer(), nullable=True),
    sa.Column('current_period_gross', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('previous_period_gross', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('gross_variance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('gross_variance_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('current_period_net', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('previous_period_net', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('net_variance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('net_variance_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('current_employee_count', sa.Integer(), nullable=False),
    sa.Column('previous_employee_count', sa.Integer(), nullable=True),
    sa.Column('new_joiners', sa.Integer(), nullable=True),
    sa.Column('exits', sa.Integer(), nullable=True),
    sa.Column('component_variance_details', sa.JSON(), nullable=True),
    sa.Column('issues_found', sa.Integer(), nullable=True),
    sa.Column('issues_resolved', sa.Integer(), nullable=True),
    sa.Column('issues_pending', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('report_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], ),
    sa.ForeignKeyConstraint(['previous_period_id'], ['payroll_periods.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reconciliation_number')
    )
    op.create_index(op.f('ix_payroll_reconciliations_id'), 'payroll_reconciliations', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_reconciliations_organization_id'), 'payroll_reconciliations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_payroll_reconciliations_payroll_period_id'), 'payroll_reconciliations', ['payroll_period_id'], unique=False)
    op.create_index(op.f('ix_payroll_reconciliations_uuid'), 'payroll_reconciliations', ['uuid'], unique=True)
    op.create_table('salary_template_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('calculation_type_override', sa.Enum('FIXED', 'PERCENTAGE', 'FORMULA', 'ATTENDANCE_BASED', 'PERFORMANCE_BASED', name='calculationtype'), nullable=True),
    sa.Column('calculation_value_override', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('formula_override', sa.Text(), nullable=True),
    sa.Column('min_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['salary_components.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['salary_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_template_comp', 'salary_template_components', ['template_id', 'component_id'], unique=True)
    op.create_index(op.f('ix_salary_template_components_id'), 'salary_template_components', ['id'], unique=False)
    op.create_index(op.f('ix_salary_template_components_template_id'), 'salary_template_components', ['template_id'], unique=False)
    op.create_table('tax_declaration_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_declaration_id', sa.Integer(), nullable=False),
    sa.Column('tax_section', sa.String(length=20), nullable=False),
    sa.Column('investment_type', sa.String(length=100), nullable=False),
    sa.Column('declared_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('section_limit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('proof_url', sa.String(length=500), nullable=True),
    sa.Column('proof_number', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('is_rejected', sa.Boolean(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tax_declaration_id'], ['tax_declarations.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_declaration_items_id'), 'tax_declaration_items', ['id'], unique=False)
    op.create_index(op.f('ix_tax_declaration_items_tax_declaration_id'), 'tax_declaration_items', ['tax_declaration_id'], unique=False)
    op.create_table('employee_salary_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_salary_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('monthly_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('annual_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('calculation_type', sa.Enum('FIXED', 'PERCENTAGE', 'FORMULA', 'ATTENDANCE_BASED', 'PERFORMANCE_BASED', name='calculationtype'), nullable=False),
    sa.Column('calculation_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('calculation_formula', sa.Text(), nullable=True),
    sa.Column('calculated_on', sa.JSON(), nullable=True),
    sa.Column('is_override', sa.Boolean(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['salary_components.id'], ),
    sa.ForeignKeyConstraint(['employee_salary_id'], ['employee_salaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_emp_sal_comp', 'employee_salary_components', ['employee_salary_id', 'component_id'], unique=False)
    op.create_index(op.f('ix_employee_salary_components_employee_salary_id'), 'employee_salary_components', ['employee_salary_id'], unique=False)
    op.create_index(op.f('ix_employee_salary_components_id'), 'employee_salary_components', ['id'], unique=False)
    op.create_table('payroll_journal_entry_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=200), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('cost_center_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('debit_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('credit_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['salary_components.id'], ),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['payroll_journal_entries.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_journal_entry_lines_id'), 'payroll_journal_entry_lines', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_journal_entry_lines_journal_entry_id'), 'payroll_journal_entry_lines', ['journal_entry_id'], unique=False)
    op.create_table('payslips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('payroll_period_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('employee_salary_id', sa.Integer(), nullable=False),
    sa.Column('payslip_number', sa.String(length=50), nullable=False),
    sa.Column('period_start_date', sa.Date(), nullable=False),
    sa.Column('period_end_date', sa.Date(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('total_working_days', sa.Integer(), nullable=False),
    sa.Column('days_present', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('days_absent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('days_on_leave', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('paid_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('lop_days', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('lop_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('basic_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_earnings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_employer_contributions', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('monthly_ctc', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('arrears_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('arrears_description', sa.Text(), nullable=True),
    sa.Column('one_time_payments', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('one_time_description', sa.Text(), nullable=True),
    sa.Column('overtime_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('overtime_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_reimbursements', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_deducted', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ytd_gross', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ytd_deductions', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ytd_net', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ytd_tax', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('payment_mode', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('GENERATED', 'PUBLISHED', 'SENT', 'VIEWED', 'DOWNLOADED', name='payslipstatus'), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('first_viewed_at', sa.DateTime(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('is_on_hold', sa.Boolean(), nullable=True),
    sa.Column('hold_reason', sa.Text(), nullable=True),
    sa.Column('payslip_pdf_url', sa.String(length=500), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(), nullable=True),
    sa.Column('reversed_by', sa.Integer(), nullable=True),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.Column('reversed_payslip_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['employee_bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_salary_id'], ['employee_salaries.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], ),
    sa.ForeignKeyConstraint(['reversed_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['reversed_payslip_id'], ['payslips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payslip_emp_fy', 'payslips', ['employee_id', 'period_start_date', 'period_end_date'], unique=False)
    op.create_index('idx_payslip_emp_period', 'payslips', ['employee_id', 'period_start_date'], unique=False)
    op.create_index('idx_payslip_period_emp', 'payslips', ['payroll_period_id', 'employee_id'], unique=True)
    op.create_index('idx_payslip_status', 'payslips', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_payslips_employee_id'), 'payslips', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payslips_id'), 'payslips', ['id'], unique=False)
    op.create_index(op.f('ix_payslips_is_on_hold'), 'payslips', ['is_on_hold'], unique=False)
    op.create_index(op.f('ix_payslips_is_published'), 'payslips', ['is_published'], unique=False)
    op.create_index(op.f('ix_payslips_organization_id'), 'payslips', ['organization_id'], unique=False)
    op.create_index(op.f('ix_payslips_payroll_period_id'), 'payslips', ['payroll_period_id'], unique=False)
    op.create_index(op.f('ix_payslips_payslip_number'), 'payslips', ['payslip_number'], unique=True)
    op.create_index(op.f('ix_payslips_status'), 'payslips', ['status'], unique=False)
    op.create_index(op.f('ix_payslips_uuid'), 'payslips', ['uuid'], unique=True)
    op.create_table('arrears',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('arrear_number', sa.String(length=50), nullable=False),
    sa.Column('arrear_type', sa.String(length=50), nullable=False),
    sa.Column('arrear_from_date', sa.Date(), nullable=False),
    sa.Column('arrear_to_date', sa.Date(), nullable=False),
    sa.Column('number_of_months', sa.Integer(), nullable=False),
    sa.Column('arrear_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_taxable', sa.Boolean(), nullable=True),
    sa.Column('tax_deducted', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('payslip_id', sa.Integer(), nullable=True),
    sa.Column('payroll_period_id', sa.Integer(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], ),
    sa.ForeignKeyConstraint(['payslip_id'], ['payslips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('arrear_number')
    )
    op.create_index(op.f('ix_arrears_employee_id'), 'arrears', ['employee_id'], unique=False)
    op.create_index(op.f('ix_arrears_id'), 'arrears', ['id'], unique=False)
    op.create_index(op.f('ix_arrears_organization_id'), 'arrears', ['organization_id'], unique=False)
    op.create_index(op.f('ix_arrears_status'), 'arrears', ['status'], unique=False)
    op.create_index(op.f('ix_arrears_uuid'), 'arrears', ['uuid'], unique=True)
    op.create_table('bank_file_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_file_id', sa.Integer(), nullable=False),
    sa.Column('payslip_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('employee_name', sa.String(length=200), nullable=False),
    sa.Column('bank_account_number', sa.String(length=50), nullable=False),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=150), nullable=True),
    sa.Column('net_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('utr_number', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bank_file_id'], ['bank_files.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payslip_id'], ['payslips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_file_records_bank_file_id'), 'bank_file_records', ['bank_file_id'], unique=False)
    op.create_index(op.f('ix_bank_file_records_id'), 'bank_file_records', ['id'], unique=False)
    op.create_table('loan_repayments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('interest_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payslip_id', sa.Integer(), nullable=True),
    sa.Column('payroll_period_id', sa.Integer(), nullable=True),
    sa.Column('outstanding_balance_after_payment', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['employee_loans.id'], ),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], ),
    sa.ForeignKeyConstraint(['payslip_id'], ['payslips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_loan_repay_due', 'loan_repayments', ['loan_id', 'due_date'], unique=False)
    op.create_index('idx_loan_repay_status', 'loan_repayments', ['is_paid', 'due_date'], unique=False)
    op.create_index(op.f('ix_loan_repayments_due_date'), 'loan_repayments', ['due_date'], unique=False)
    op.create_index(op.f('ix_loan_repayments_id'), 'loan_repayments', ['id'], unique=False)
    op.create_index(op.f('ix_loan_repayments_is_paid'), 'loan_repayments', ['is_paid'], unique=False)
    op.create_index(op.f('ix_loan_repayments_loan_id'), 'loan_repayments', ['loan_id'], unique=False)
    op.create_table('one_time_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('payment_number', sa.String(length=50), nullable=False),
    sa.Column('payment_type', sa.String(length=50), nullable=False),
    sa.Column('payment_name', sa.String(length=150), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_taxable', sa.Boolean(), nullable=True),
    sa.Column('tax_deducted', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payment_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('payslip_id', sa.Integer(), nullable=True),
    sa.Column('payroll_period_id', sa.Integer(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], ),
    sa.ForeignKeyConstraint(['payslip_id'], ['payslips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_number')
    )
    op.create_index(op.f('ix_one_time_payments_employee_id'), 'one_time_payments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_one_time_payments_id'), 'one_time_payments', ['id'], unique=False)
    op.create_index(op.f('ix_one_time_payments_organization_id'), 'one_time_payments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_one_time_payments_status'), 'one_time_payments', ['status'], unique=False)
    op.create_index(op.f('ix_one_time_payments_uuid'), 'one_time_payments', ['uuid'], unique=True)
    op.create_table('payroll_reconciliation_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reconciliation_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('payslip_id', sa.Integer(), nullable=True),
    sa.Column('issue_type', sa.String(length=50), nullable=False),
    sa.Column('issue_description', sa.Text(), nullable=False),
    sa.Column('financial_impact', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payslip_id'], ['payslips.id'], ),
    sa.ForeignKeyConstraint(['reconciliation_id'], ['payroll_reconciliations.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_reconciliation_issues_id'), 'payroll_reconciliation_issues', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_reconciliation_issues_reconciliation_id'), 'payroll_reconciliation_issues', ['reconciliation_id'], unique=False)
    op.create_table('payslip_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payslip_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('component_name', sa.String(length=150), nullable=False),
    sa.Column('component_type', sa.Enum('EARNING', 'DEDUCTION', 'EMPLOYER_CONTRIBUTION', name='componenttype'), nullable=False),
    sa.Column('monthly_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_prorated', sa.Boolean(), nullable=True),
    sa.Column('proration_days', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('proration_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ytd_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('calculation_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['salary_components.id'], ),
    sa.ForeignKeyConstraint(['payslip_id'], ['payslips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payslip_components_id'), 'payslip_components', ['id'], unique=False)
    op.create_index(op.f('ix_payslip_components_payslip_id'), 'payslip_components', ['payslip_id'], unique=False)
    op.create_table('reimbursement_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', app.models.organization.GUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('claim_number', sa.String(length=50), nullable=False),
    sa.Column('claim_date', sa.Date(), nullable=False),
    sa.Column('claimed_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('merchant_name', sa.String(length=200), nullable=True),
    sa.Column('receipt_urls', sa.JSON(), nullable=True),
    sa.Column('receipt_numbers', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'PAID', name='reimbursementstatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approver_comments', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('payslip_id', sa.Integer(), nullable=True),
    sa.Column('payroll_period_id', sa.Integer(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['reimbursement_categories.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], ),
    sa.ForeignKeyConstraint(['payslip_id'], ['payslips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reimb_claim_approver', 'reimbursement_claims', ['approver_id', 'status'], unique=False)
    op.create_index('idx_reimb_claim_emp_status', 'reimbursement_claims', ['employee_id', 'status'], unique=False)
    op.create_index(op.f('ix_reimbursement_claims_approver_id'), 'reimbursement_claims', ['approver_id'], unique=False)
    op.create_index(op.f('ix_reimbursement_claims_claim_number'), 'reimbursement_claims', ['claim_number'], unique=True)
    op.create_index(op.f('ix_reimbursement_claims_employee_id'), 'reimbursement_claims', ['employee_id'], unique=False)
    op.create_index(op.f('ix_reimbursement_claims_id'), 'reimbursement_claims', ['id'], unique=False)
    op.create_index(op.f('ix_reimbursement_claims_organization_id'), 'reimbursement_claims', ['organization_id'], unique=False)
    op.create_index(op.f('ix_reimbursement_claims_status'), 'reimbursement_claims', ['status'], unique=False)
    op.create_index(op.f('ix_reimbursement_claims_uuid'), 'reimbursement_claims', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reimbursement_claims_uuid'), table_name='reimbursement_claims')
    op.drop_index(op.f('ix_reimbursement_claims_status'), table_name='reimbursement_claims')
    op.drop_index(op.f('ix_reimbursement_claims_organization_id'), table_name='reimbursement_claims')
    op.drop_index(op.f('ix_reimbursement_claims_id'), table_name='reimbursement_claims')
    op.drop_index(op.f('ix_reimbursement_claims_employee_id'), table_name='reimbursement_claims')
    op.drop_index(op.f('ix_reimbursement_claims_claim_number'), table_name='reimbursement_claims')
    op.drop_index(op.f('ix_reimbursement_claims_approver_id'), table_name='reimbursement_claims')
    op.drop_index('idx_reimb_claim_emp_status', table_name='reimbursement_claims')
    op.drop_index('idx_reimb_claim_approver', table_name='reimbursement_claims')
    op.drop_table('reimbursement_claims')
    op.drop_index(op.f('ix_payslip_components_payslip_id'), table_name='payslip_components')
    op.drop_index(op.f('ix_payslip_components_id'), table_name='payslip_components')
    op.drop_table('payslip_components')
    op.drop_index(op.f('ix_payroll_reconciliation_issues_reconciliation_id'), table_name='payroll_reconciliation_issues')
    op.drop_index(op.f('ix_payroll_reconciliation_issues_id'), table_name='payroll_reconciliation_issues')
    op.drop_table('payroll_reconciliation_issues')
    op.drop_index(op.f('ix_one_time_payments_uuid'), table_name='one_time_payments')
    op.drop_index(op.f('ix_one_time_payments_status'), table_name='one_time_payments')
    op.drop_index(op.f('ix_one_time_payments_organization_id'), table_name='one_time_payments')
    op.drop_index(op.f('ix_one_time_payments_id'), table_name='one_time_payments')
    op.drop_index(op.f('ix_one_time_payments_employee_id'), table_name='one_time_payments')
    op.drop_table('one_time_payments')
    op.drop_index(op.f('ix_loan_repayments_loan_id'), table_name='loan_repayments')
    op.drop_index(op.f('ix_loan_repayments_is_paid'), table_name='loan_repayments')
    op.drop_index(op.f('ix_loan_repayments_id'), table_name='loan_repayments')
    op.drop_index(op.f('ix_loan_repayments_due_date'), table_name='loan_repayments')
    op.drop_index('idx_loan_repay_status', table_name='loan_repayments')
    op.drop_index('idx_loan_repay_due', table_name='loan_repayments')
    op.drop_table('loan_repayments')
    op.drop_index(op.f('ix_bank_file_records_id'), table_name='bank_file_records')
    op.drop_index(op.f('ix_bank_file_records_bank_file_id'), table_name='bank_file_records')
    op.drop_table('bank_file_records')
    op.drop_index(op.f('ix_arrears_uuid'), table_name='arrears')
    op.drop_index(op.f('ix_arrears_status'), table_name='arrears')
    op.drop_index(op.f('ix_arrears_organization_id'), table_name='arrears')
    op.drop_index(op.f('ix_arrears_id'), table_name='arrears')
    op.drop_index(op.f('ix_arrears_employee_id'), table_name='arrears')
    op.drop_table('arrears')
    op.drop_index(op.f('ix_payslips_uuid'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_status'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_payslip_number'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_payroll_period_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_organization_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_is_published'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_is_on_hold'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_employee_id'), table_name='payslips')
    op.drop_index('idx_payslip_status', table_name='payslips')
    op.drop_index('idx_payslip_period_emp', table_name='payslips')
    op.drop_index('idx_payslip_emp_period', table_name='payslips')
    op.drop_index('idx_payslip_emp_fy', table_name='payslips')
    op.drop_table('payslips')
    op.drop_index(op.f('ix_payroll_journal_entry_lines_journal_entry_id'), table_name='payroll_journal_entry_lines')
    op.drop_index(op.f('ix_payroll_journal_entry_lines_id'), table_name='payroll_journal_entry_lines')
    op.drop_table('payroll_journal_entry_lines')
    op.drop_index(op.f('ix_employee_salary_components_id'), table_name='employee_salary_components')
    op.drop_index(op.f('ix_employee_salary_components_employee_salary_id'), table_name='employee_salary_components')
    op.drop_index('idx_emp_sal_comp', table_name='employee_salary_components')
    op.drop_table('employee_salary_components')
    op.drop_index(op.f('ix_tax_declaration_items_tax_declaration_id'), table_name='tax_declaration_items')
    op.drop_index(op.f('ix_tax_declaration_items_id'), table_name='tax_declaration_items')
    op.drop_table('tax_declaration_items')
    op.drop_index(op.f('ix_salary_template_components_template_id'), table_name='salary_template_components')
    op.drop_index(op.f('ix_salary_template_components_id'), table_name='salary_template_components')
    op.drop_index('idx_template_comp', table_name='salary_template_components')
    op.drop_table('salary_template_components')
    op.drop_index(op.f('ix_payroll_reconciliations_uuid'), table_name='payroll_reconciliations')
    op.drop_index(op.f('ix_payroll_reconciliations_payroll_period_id'), table_name='payroll_reconciliations')
    op.drop_index(op.f('ix_payroll_reconciliations_organization_id'), table_name='payroll_reconciliations')
    op.drop_index(op.f('ix_payroll_reconciliations_id'), table_name='payroll_reconciliations')
    op.drop_table('payroll_reconciliations')
    op.drop_index(op.f('ix_payroll_journal_entries_uuid'), table_name='payroll_journal_entries')
    op.drop_index(op.f('ix_payroll_journal_entries_payroll_period_id'), table_name='payroll_journal_entries')
    op.drop_index(op.f('ix_payroll_journal_entries_organization_id'), table_name='payroll_journal_entries')
    op.drop_index(op.f('ix_payroll_journal_entries_id'), table_name='payroll_journal_entries')
    op.drop_table('payroll_journal_entries')
    op.drop_index(op.f('ix_employee_salaries_uuid'), table_name='employee_salaries')
    op.drop_index(op.f('ix_employee_salaries_organization_id'), table_name='employee_salaries')
    op.drop_index(op.f('ix_employee_salaries_is_on_hold'), table_name='employee_salaries')
    op.drop_index(op.f('ix_employee_salaries_is_active'), table_name='employee_salaries')
    op.drop_index(op.f('ix_employee_salaries_id'), table_name='employee_salaries')
    op.drop_index(op.f('ix_employee_salaries_employee_id'), table_name='employee_salaries')
    op.drop_index(op.f('ix_employee_salaries_effective_to'), table_name='employee_salaries')
    op.drop_index(op.f('ix_employee_salaries_effective_from'), table_name='employee_salaries')
    op.drop_index('idx_emp_sal_emp_active', table_name='employee_salaries')
    op.drop_index('idx_emp_sal_effective', table_name='employee_salaries')
    op.drop_table('employee_salaries')
    op.drop_index(op.f('ix_bank_files_uuid'), table_name='bank_files')
    op.drop_index(op.f('ix_bank_files_payroll_period_id'), table_name='bank_files')
    op.drop_index(op.f('ix_bank_files_organization_id'), table_name='bank_files')
    op.drop_index(op.f('ix_bank_files_id'), table_name='bank_files')
    op.drop_table('bank_files')
    op.drop_index(op.f('ix_tax_declarations_uuid'), table_name='tax_declarations')
    op.drop_index(op.f('ix_tax_declarations_status'), table_name='tax_declarations')
    op.drop_index(op.f('ix_tax_declarations_organization_id'), table_name='tax_declarations')
    op.drop_index(op.f('ix_tax_declarations_id'), table_name='tax_declarations')
    op.drop_index(op.f('ix_tax_declarations_employee_id'), table_name='tax_declarations')
    op.drop_index('idx_tax_decl_emp_status', table_name='tax_declarations')
    op.drop_index('idx_tax_decl_emp_fy', table_name='tax_declarations')
    op.drop_table('tax_declarations')
    op.drop_index(op.f('ix_tax_calculations_uuid'), table_name='tax_calculations')
    op.drop_index(op.f('ix_tax_calculations_organization_id'), table_name='tax_calculations')
    op.drop_index(op.f('ix_tax_calculations_id'), table_name='tax_calculations')
    op.drop_index(op.f('ix_tax_calculations_employee_id'), table_name='tax_calculations')
    op.drop_index('idx_tax_calc_emp_fy', table_name='tax_calculations')
    op.drop_table('tax_calculations')
    op.drop_index(op.f('ix_statutory_forms_uuid'), table_name='statutory_forms')
    op.drop_index(op.f('ix_statutory_forms_organization_id'), table_name='statutory_forms')
    op.drop_index(op.f('ix_statutory_forms_id'), table_name='statutory_forms')
    op.drop_table('statutory_forms')
    op.drop_index(op.f('ix_salary_templates_uuid'), table_name='salary_templates')
    op.drop_index(op.f('ix_salary_templates_organization_id'), table_name='salary_templates')
    op.drop_index(op.f('ix_salary_templates_id'), table_name='salary_templates')
    op.drop_index('idx_sal_template_org_code', table_name='salary_templates')
    op.drop_table('salary_templates')
    op.drop_index(op.f('ix_salary_components_uuid'), table_name='salary_components')
    op.drop_index(op.f('ix_salary_components_organization_id'), table_name='salary_components')
    op.drop_index(op.f('ix_salary_components_is_active'), table_name='salary_components')
    op.drop_index(op.f('ix_salary_components_id'), table_name='salary_components')
    op.drop_index(op.f('ix_salary_components_component_code'), table_name='salary_components')
    op.drop_index('idx_sal_comp_org_code', table_name='salary_components')
    op.drop_table('salary_components')
    op.drop_index(op.f('ix_reimbursement_categories_organization_id'), table_name='reimbursement_categories')
    op.drop_index(op.f('ix_reimbursement_categories_id'), table_name='reimbursement_categories')
    op.drop_index('idx_reimb_cat_org_code', table_name='reimbursement_categories')
    op.drop_table('reimbursement_categories')
    op.drop_index(op.f('ix_payroll_periods_uuid'), table_name='payroll_periods')
    op.drop_index(op.f('ix_payroll_periods_status'), table_name='payroll_periods')
    op.drop_index(op.f('ix_payroll_periods_period_start_date'), table_name='payroll_periods')
    op.drop_index(op.f('ix_payroll_periods_period_end_date'), table_name='payroll_periods')
    op.drop_index(op.f('ix_payroll_periods_organization_id'), table_name='payroll_periods')
    op.drop_index(op.f('ix_payroll_periods_is_locked'), table_name='payroll_periods')
    op.drop_index(op.f('ix_payroll_periods_id'), table_name='payroll_periods')
    op.drop_index('idx_payroll_period_status', table_name='payroll_periods')
    op.drop_index('idx_payroll_period_org_code', table_name='payroll_periods')
    op.drop_index('idx_payroll_period_fy_status', table_name='payroll_periods')
    op.drop_index('idx_payroll_period_dates', table_name='payroll_periods')
    op.drop_table('payroll_periods')
    op.drop_index(op.f('ix_payroll_audit_logs_performed_by'), table_name='payroll_audit_logs')
    op.drop_index(op.f('ix_payroll_audit_logs_performed_at'), table_name='payroll_audit_logs')
    op.drop_index(op.f('ix_payroll_audit_logs_organization_id'), table_name='payroll_audit_logs')
    op.drop_index(op.f('ix_payroll_audit_logs_id'), table_name='payroll_audit_logs')
    op.drop_index(op.f('ix_payroll_audit_logs_entity_id'), table_name='payroll_audit_logs')
    op.drop_index(op.f('ix_payroll_audit_logs_employee_id'), table_name='payroll_audit_logs')
    op.drop_index(op.f('ix_payroll_audit_logs_action_type'), table_name='payroll_audit_logs')
    op.drop_index('idx_payroll_audit_entity', table_name='payroll_audit_logs')
    op.drop_index('idx_payroll_audit_action', table_name='payroll_audit_logs')
    op.drop_table('payroll_audit_logs')
    op.drop_index(op.f('ix_final_settlements_uuid'), table_name='final_settlements')
    op.drop_index(op.f('ix_final_settlements_status'), table_name='final_settlements')
    op.drop_index(op.f('ix_final_settlements_settlement_number'), table_name='final_settlements')
    op.drop_index(op.f('ix_final_settlements_organization_id'), table_name='final_settlements')
    op.drop_index(op.f('ix_final_settlements_id'), table_name='final_settlements')
    op.drop_index(op.f('ix_final_settlements_employee_id'), table_name='final_settlements')
    op.drop_table('final_settlements')
    op.drop_index(op.f('ix_employee_loans_uuid'), table_name='employee_loans')
    op.drop_index(op.f('ix_employee_loans_status'), table_name='employee_loans')
    op.drop_index(op.f('ix_employee_loans_organization_id'), table_name='employee_loans')
    op.drop_index(op.f('ix_employee_loans_loan_number'), table_name='employee_loans')
    op.drop_index(op.f('ix_employee_loans_id'), table_name='employee_loans')
    op.drop_index(op.f('ix_employee_loans_employee_id'), table_name='employee_loans')
    op.drop_index('idx_loan_emp_status', table_name='employee_loans')
    op.drop_table('employee_loans')
    # ### end Alembic commands ###
