"""add soft delete fields to leave policies

Revision ID: f82670a6e97e
Revises: b48f1f322303
Create Date: 2026-02-03 15:51:02.806668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f82670a6e97e'
down_revision: Union[str, Sequence[str], None] = 'b48f1f322303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_policies', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('leave_policies', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_leave_policies_is_deleted'), 'leave_policies', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leave_policies_is_deleted'), table_name='leave_policies')
    op.drop_column('leave_policies', 'deleted_at')
    op.drop_column('leave_policies', 'is_deleted')
    # ### end Alembic commands ###
